#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Position
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Position/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Positions.EditPositionViewModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\Position\Edit.cshtml"
  
    string action = Model.Id == 0 ? "Add" : "Edit";
    ViewBag.Title = action + " Position";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"lineSeperater\"> \r\n        <div " +
"class=\"pageInfoBox\"> \r\n");


            
            #line 11 "..\..\Views\Position\Edit.cshtml"
             using (Html.BeginForm(MVC.Position.Edit()))
            {
                
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Position\Edit.cshtml"
           Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Position\Edit.cshtml"
                                          
                
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Position\Edit.cshtml"
           Write(Html.HiddenFor(x => x.Company.Id));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Position\Edit.cshtml"
                                                  


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"grid3 marginBottom_10 marginAuto floatLeft\"> \r\n      " +
"                  <h3 class=\"floatLeft\">");


            
            #line 17 "..\..\Views\Position\Edit.cshtml"
                                         Write(action);

            
            #line default
            #line hidden
WriteLiteral(" Position</h3> \r\n                </div> \r\n");


            
            #line 19 "..\..\Views\Position\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                 " +
"   <div class=\"floatLeft\"><p class=\"greyHighlight\">Title:</p>\r\n                 " +
"       <div class=\"infoSpan\">");


            
            #line 22 "..\..\Views\Position\Edit.cshtml"
                                         Write(Html.TextBoxFor(x => x.Title, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div> \r\n                </div> \r\n");


            
            #line 25 "..\..\Views\Position\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                 " +
"   <div class=\"floatLeft\"><p class=\"greyHighlight\">Have You Applied Yet?</p>\r\n  " +
"                      <div class=\"infoSpan\">\r\n                            ");


            
            #line 29 "..\..\Views\Position\Edit.cshtml"
                       Write(Html.CheckBoxFor(x => x.HasApplied));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div> \r\n                </" +
"div> \r\n");


            
            #line 33 "..\..\Views\Position\Edit.cshtml"
 

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                 " +
"   <div class=\"floatLeft\"><p class=\"greyHighlight\">Notes:</p>\r\n                 " +
"       <div class=\"infoSpan\">");


            
            #line 36 "..\..\Views\Position\Edit.cshtml"
                                         Write(Html.TextAreaFor(x => x.Notes, new { @class = "textAreaInfo" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div> \r\n                </div> \r\n");


            
            #line 39 "..\..\Views\Position\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"grid3 marginBottom_20 floatLeft\"> \r\n                 " +
"   <div class=\"submitBTN \">\r\n                        <input type=\"submit\" value=" +
"\"Save\" /> &nbsp;\r\n");


            
            #line 43 "..\..\Views\Position\Edit.cshtml"
                         if (Model.Id != 0)
                        {
                            
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Position\Edit.cshtml"
                       Write(Html.ActionLink("Cancel", MVC.Position.Details(Model.Id)));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Position\Edit.cshtml"
                                                                                      
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Position\Edit.cshtml"
                       Write(Html.ActionLink("Cancel", MVC.Company.Details(Model.Company.Id)));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Position\Edit.cshtml"
                                                                                             
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div> \r\n                </div> \r\n");


            
            #line 53 "..\..\Views\Position\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"clear\"></div> \r\n        </div> \r\n    </div> \r\n</div> \r\n\r\n" +
"");


            
            #line 59 "..\..\Views\Position\Edit.cshtml"
  Html.RenderPartial(MVC.Company.Views._CompanySummaryDisplay, Model.Company);

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
