using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MyJobLeads.Areas.PositionSearch.Models
{
    public class PositionSearchQueryViewModel
    {
        public string Keywords { get; set; }
        public string SelectedCountryCode { get; set; }
        public string PostalCode { get; set; }
        public IList<SelectListItem> CountryCodeList { get; set; }

        public PositionSearchQueryViewModel()
        {
            // Default the country code to US
            SelectedCountryCode = "US";

            CountryCodeList = new List<SelectListItem>();
            CountryCodeList.Add(new SelectListItem { Value = "AD", Text = "Andorra" });
            CountryCodeList.Add(new SelectListItem { Value = "AE", Text = "United Arab Emirates" });
            CountryCodeList.Add(new SelectListItem { Value = "AF", Text = "Afghanistan" });
            CountryCodeList.Add(new SelectListItem { Value = "AG", Text = "Antigua and Barbuda" });
            CountryCodeList.Add(new SelectListItem { Value = "AI", Text = "Anguilla" });
            CountryCodeList.Add(new SelectListItem { Value = "AL", Text = "Albania" });
            CountryCodeList.Add(new SelectListItem { Value = "AM", Text = "Armenia" });
            CountryCodeList.Add(new SelectListItem { Value = "AN", Text = "Netherlands Antilles" });
            CountryCodeList.Add(new SelectListItem { Value = "AO", Text = "Angola" });
            CountryCodeList.Add(new SelectListItem { Value = "AQ", Text = "Antarctica" });
            CountryCodeList.Add(new SelectListItem { Value = "AR", Text = "Argentina" });
            CountryCodeList.Add(new SelectListItem { Value = "AS", Text = "American Samoa" });
            CountryCodeList.Add(new SelectListItem { Value = "AT", Text = "Austria" });
            CountryCodeList.Add(new SelectListItem { Value = "AU", Text = "Australia" });
            CountryCodeList.Add(new SelectListItem { Value = "AW", Text = "Aruba" });
            CountryCodeList.Add(new SelectListItem { Value = "AX", Text = "Aland Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "AZ", Text = "Azerbaijan" });
            CountryCodeList.Add(new SelectListItem { Value = "BA", Text = "Bosnia and Herzegovina" });
            CountryCodeList.Add(new SelectListItem { Value = "BB", Text = "Barbados" });
            CountryCodeList.Add(new SelectListItem { Value = "BD", Text = "Bangladesh" });
            CountryCodeList.Add(new SelectListItem { Value = "BE", Text = "Belgium" });
            CountryCodeList.Add(new SelectListItem { Value = "BF", Text = "Burkina Faso" });
            CountryCodeList.Add(new SelectListItem { Value = "BG", Text = "Bulgaria" });
            CountryCodeList.Add(new SelectListItem { Value = "BH", Text = "Bahrain" });
            CountryCodeList.Add(new SelectListItem { Value = "BI", Text = "Burundi" });
            CountryCodeList.Add(new SelectListItem { Value = "BJ", Text = "Benin" });
            CountryCodeList.Add(new SelectListItem { Value = "BM", Text = "Bermuda" });
            CountryCodeList.Add(new SelectListItem { Value = "BN", Text = "Brunei Darussalam" });
            CountryCodeList.Add(new SelectListItem { Value = "BO", Text = "Bolivia" });
            CountryCodeList.Add(new SelectListItem { Value = "BR", Text = "Brazil" });
            CountryCodeList.Add(new SelectListItem { Value = "BS", Text = "Bahamas" });
            CountryCodeList.Add(new SelectListItem { Value = "BT", Text = "Bhutan" });
            CountryCodeList.Add(new SelectListItem { Value = "BV", Text = "Bouvet Island" });
            CountryCodeList.Add(new SelectListItem { Value = "BW", Text = "Botswana" });
            CountryCodeList.Add(new SelectListItem { Value = "BY", Text = "Belarus" });
            CountryCodeList.Add(new SelectListItem { Value = "BZ", Text = "Belize" });
            CountryCodeList.Add(new SelectListItem { Value = "CA", Text = "Canada" });
            CountryCodeList.Add(new SelectListItem { Value = "CC", Text = "Cocos (Keeling) Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "CD", Text = "Democratic Republic of the Congo" });
            CountryCodeList.Add(new SelectListItem { Value = "CF", Text = "Central African Republic" });
            CountryCodeList.Add(new SelectListItem { Value = "CG", Text = "Congo" });
            CountryCodeList.Add(new SelectListItem { Value = "CH", Text = "Switzerland" });
            CountryCodeList.Add(new SelectListItem { Value = "CI", Text = "Cote D'Ivoire (Ivory Coast)" });
            CountryCodeList.Add(new SelectListItem { Value = "CK", Text = "Cook Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "CL", Text = "Chile" });
            CountryCodeList.Add(new SelectListItem { Value = "CM", Text = "Cameroon" });
            CountryCodeList.Add(new SelectListItem { Value = "CN", Text = "China" });
            CountryCodeList.Add(new SelectListItem { Value = "CO", Text = "Colombia" });
            CountryCodeList.Add(new SelectListItem { Value = "CR", Text = "Costa Rica" });
            CountryCodeList.Add(new SelectListItem { Value = "CS", Text = "Serbia and Montenegro" });
            CountryCodeList.Add(new SelectListItem { Value = "CU", Text = "Cuba" });
            CountryCodeList.Add(new SelectListItem { Value = "CV", Text = "Cape Verde" });
            CountryCodeList.Add(new SelectListItem { Value = "CX", Text = "Christmas Island" });
            CountryCodeList.Add(new SelectListItem { Value = "CY", Text = "Cyprus" });
            CountryCodeList.Add(new SelectListItem { Value = "CZ", Text = "Czech Republic" });
            CountryCodeList.Add(new SelectListItem { Value = "DE", Text = "Germany" });
            CountryCodeList.Add(new SelectListItem { Value = "DJ", Text = "Djibouti" });
            CountryCodeList.Add(new SelectListItem { Value = "DK", Text = "Denmark" });
            CountryCodeList.Add(new SelectListItem { Value = "DM", Text = "Dominica" });
            CountryCodeList.Add(new SelectListItem { Value = "DO", Text = "Dominican Republic" });
            CountryCodeList.Add(new SelectListItem { Value = "DZ", Text = "Algeria" });
            CountryCodeList.Add(new SelectListItem { Value = "EC", Text = "Ecuador" });
            CountryCodeList.Add(new SelectListItem { Value = "EE", Text = "Estonia" });
            CountryCodeList.Add(new SelectListItem { Value = "EG", Text = "Egypt" });
            CountryCodeList.Add(new SelectListItem { Value = "EH", Text = "Western Sahara" });
            CountryCodeList.Add(new SelectListItem { Value = "ER", Text = "Eritrea" });
            CountryCodeList.Add(new SelectListItem { Value = "ES", Text = "Spain" });
            CountryCodeList.Add(new SelectListItem { Value = "ET", Text = "Ethiopia" });
            CountryCodeList.Add(new SelectListItem { Value = "FI", Text = "Finland" });
            CountryCodeList.Add(new SelectListItem { Value = "FJ", Text = "Fiji" });
            CountryCodeList.Add(new SelectListItem { Value = "FK", Text = "Falkland Islands (Malvinas)" });
            CountryCodeList.Add(new SelectListItem { Value = "FM", Text = "Federated States of Micronesia" });
            CountryCodeList.Add(new SelectListItem { Value = "FO", Text = "Faroe Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "FR", Text = "France" });
            CountryCodeList.Add(new SelectListItem { Value = "FX", Text = "France, Metropolitan" });
            CountryCodeList.Add(new SelectListItem { Value = "GA", Text = "Gabon" });
            CountryCodeList.Add(new SelectListItem { Value = "GB", Text = "Great Britain (UK)" });
            CountryCodeList.Add(new SelectListItem { Value = "GD", Text = "Grenada" });
            CountryCodeList.Add(new SelectListItem { Value = "GE", Text = "Georgia" });
            CountryCodeList.Add(new SelectListItem { Value = "GF", Text = "French Guiana" });
            CountryCodeList.Add(new SelectListItem { Value = "GH", Text = "Ghana" });
            CountryCodeList.Add(new SelectListItem { Value = "GI", Text = "Gibraltar" });
            CountryCodeList.Add(new SelectListItem { Value = "GL", Text = "Greenland" });
            CountryCodeList.Add(new SelectListItem { Value = "GM", Text = "Gambia" });
            CountryCodeList.Add(new SelectListItem { Value = "GN", Text = "Guinea" });
            CountryCodeList.Add(new SelectListItem { Value = "GP", Text = "Guadeloupe" });
            CountryCodeList.Add(new SelectListItem { Value = "GQ", Text = "Equatorial Guinea" });
            CountryCodeList.Add(new SelectListItem { Value = "GR", Text = "Greece" });
            CountryCodeList.Add(new SelectListItem { Value = "GS", Text = "S. Georgia and S. Sandwich Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "GT", Text = "Guatemala" });
            CountryCodeList.Add(new SelectListItem { Value = "GU", Text = "Guam" });
            CountryCodeList.Add(new SelectListItem { Value = "GW", Text = "Guinea-Bissau" });
            CountryCodeList.Add(new SelectListItem { Value = "GY", Text = "Guyana" });
            CountryCodeList.Add(new SelectListItem { Value = "HK", Text = "Hong Kong" });
            CountryCodeList.Add(new SelectListItem { Value = "HM", Text = "Heard Island and McDonald Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "HN", Text = "Honduras" });
            CountryCodeList.Add(new SelectListItem { Value = "HR", Text = "Croatia (Hrvatska)" });
            CountryCodeList.Add(new SelectListItem { Value = "HT", Text = "Haiti" });
            CountryCodeList.Add(new SelectListItem { Value = "HU", Text = "Hungary" });
            CountryCodeList.Add(new SelectListItem { Value = "ID", Text = "Indonesia" });
            CountryCodeList.Add(new SelectListItem { Value = "IE", Text = "Ireland" });
            CountryCodeList.Add(new SelectListItem { Value = "IL", Text = "Israel" });
            CountryCodeList.Add(new SelectListItem { Value = "IN", Text = "India" });
            CountryCodeList.Add(new SelectListItem { Value = "IO", Text = "British Indian Ocean Territory" });
            CountryCodeList.Add(new SelectListItem { Value = "IQ", Text = "Iraq" });
            CountryCodeList.Add(new SelectListItem { Value = "IR", Text = "Iran" });
            CountryCodeList.Add(new SelectListItem { Value = "IS", Text = "Iceland" });
            CountryCodeList.Add(new SelectListItem { Value = "IT", Text = "Italy" });
            CountryCodeList.Add(new SelectListItem { Value = "JM", Text = "Jamaica" });
            CountryCodeList.Add(new SelectListItem { Value = "JO", Text = "Jordan" });
            CountryCodeList.Add(new SelectListItem { Value = "JP", Text = "Japan" });
            CountryCodeList.Add(new SelectListItem { Value = "KE", Text = "Kenya" });
            CountryCodeList.Add(new SelectListItem { Value = "KG", Text = "Kyrgyzstan" });
            CountryCodeList.Add(new SelectListItem { Value = "KH", Text = "Cambodia" });
            CountryCodeList.Add(new SelectListItem { Value = "KI", Text = "Kiribati" });
            CountryCodeList.Add(new SelectListItem { Value = "KM", Text = "Comoros" });
            CountryCodeList.Add(new SelectListItem { Value = "KN", Text = "Saint Kitts and Nevis" });
            CountryCodeList.Add(new SelectListItem { Value = "KP", Text = "Korea (North)" });
            CountryCodeList.Add(new SelectListItem { Value = "KR", Text = "Korea (South)" });
            CountryCodeList.Add(new SelectListItem { Value = "KW", Text = "Kuwait" });
            CountryCodeList.Add(new SelectListItem { Value = "KY", Text = "Cayman Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "KZ", Text = "Kazakhstan" });
            CountryCodeList.Add(new SelectListItem { Value = "LA", Text = "Laos" });
            CountryCodeList.Add(new SelectListItem { Value = "LB", Text = "Lebanon" });
            CountryCodeList.Add(new SelectListItem { Value = "LC", Text = "Saint Lucia" });
            CountryCodeList.Add(new SelectListItem { Value = "LI", Text = "Liechtenstein" });
            CountryCodeList.Add(new SelectListItem { Value = "LK", Text = "Sri Lanka" });
            CountryCodeList.Add(new SelectListItem { Value = "LR", Text = "Liberia" });
            CountryCodeList.Add(new SelectListItem { Value = "LS", Text = "Lesotho" });
            CountryCodeList.Add(new SelectListItem { Value = "LT", Text = "Lithuania" });
            CountryCodeList.Add(new SelectListItem { Value = "LU", Text = "Luxembourg" });
            CountryCodeList.Add(new SelectListItem { Value = "LV", Text = "Latvia" });
            CountryCodeList.Add(new SelectListItem { Value = "LY", Text = "Libya" });
            CountryCodeList.Add(new SelectListItem { Value = "MA", Text = "Morocco" });
            CountryCodeList.Add(new SelectListItem { Value = "MC", Text = "Monaco" });
            CountryCodeList.Add(new SelectListItem { Value = "MD", Text = "Moldova" });
            CountryCodeList.Add(new SelectListItem { Value = "MG", Text = "Madagascar" });
            CountryCodeList.Add(new SelectListItem { Value = "MH", Text = "Marshall Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "MK", Text = "Macedonia" });
            CountryCodeList.Add(new SelectListItem { Value = "ML", Text = "Mali" });
            CountryCodeList.Add(new SelectListItem { Value = "MM", Text = "Myanmar" });
            CountryCodeList.Add(new SelectListItem { Value = "MN", Text = "Mongolia" });
            CountryCodeList.Add(new SelectListItem { Value = "MO", Text = "Macao" });
            CountryCodeList.Add(new SelectListItem { Value = "MP", Text = "Northern Mariana Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "MQ", Text = "Martinique" });
            CountryCodeList.Add(new SelectListItem { Value = "MR", Text = "Mauritania" });
            CountryCodeList.Add(new SelectListItem { Value = "MS", Text = "Montserrat" });
            CountryCodeList.Add(new SelectListItem { Value = "MT", Text = "Malta" });
            CountryCodeList.Add(new SelectListItem { Value = "MU", Text = "Mauritius" });
            CountryCodeList.Add(new SelectListItem { Value = "MV", Text = "Maldives" });
            CountryCodeList.Add(new SelectListItem { Value = "MW", Text = "Malawi" });
            CountryCodeList.Add(new SelectListItem { Value = "MX", Text = "Mexico" });
            CountryCodeList.Add(new SelectListItem { Value = "MY", Text = "Malaysia" });
            CountryCodeList.Add(new SelectListItem { Value = "MZ", Text = "Mozambique" });
            CountryCodeList.Add(new SelectListItem { Value = "NA", Text = "Namibia" });
            CountryCodeList.Add(new SelectListItem { Value = "NC", Text = "New Caledonia" });
            CountryCodeList.Add(new SelectListItem { Value = "NE", Text = "Niger" });
            CountryCodeList.Add(new SelectListItem { Value = "NF", Text = "Norfolk Island" });
            CountryCodeList.Add(new SelectListItem { Value = "NG", Text = "Nigeria" });
            CountryCodeList.Add(new SelectListItem { Value = "NI", Text = "Nicaragua" });
            CountryCodeList.Add(new SelectListItem { Value = "NL", Text = "Netherlands" });
            CountryCodeList.Add(new SelectListItem { Value = "NO", Text = "Norway" });
            CountryCodeList.Add(new SelectListItem { Value = "NP", Text = "Nepal" });
            CountryCodeList.Add(new SelectListItem { Value = "NR", Text = "Nauru" });
            CountryCodeList.Add(new SelectListItem { Value = "NU", Text = "Niue" });
            CountryCodeList.Add(new SelectListItem { Value = "NZ", Text = "New Zealand (Aotearoa)" });
            CountryCodeList.Add(new SelectListItem { Value = "OM", Text = "Oman" });
            CountryCodeList.Add(new SelectListItem { Value = "PA", Text = "Panama" });
            CountryCodeList.Add(new SelectListItem { Value = "PE", Text = "Peru" });
            CountryCodeList.Add(new SelectListItem { Value = "PF", Text = "French Polynesia" });
            CountryCodeList.Add(new SelectListItem { Value = "PG", Text = "Papua New Guinea" });
            CountryCodeList.Add(new SelectListItem { Value = "PH", Text = "Philippines" });
            CountryCodeList.Add(new SelectListItem { Value = "PK", Text = "Pakistan" });
            CountryCodeList.Add(new SelectListItem { Value = "PL", Text = "Poland" });
            CountryCodeList.Add(new SelectListItem { Value = "PM", Text = "Saint Pierre and Miquelon" });
            CountryCodeList.Add(new SelectListItem { Value = "PN", Text = "Pitcairn" });
            CountryCodeList.Add(new SelectListItem { Value = "PR", Text = "Puerto Rico" });
            CountryCodeList.Add(new SelectListItem { Value = "PS", Text = "Palestinian Territory" });
            CountryCodeList.Add(new SelectListItem { Value = "PT", Text = "Portugal" });
            CountryCodeList.Add(new SelectListItem { Value = "PW", Text = "Palau" });
            CountryCodeList.Add(new SelectListItem { Value = "PY", Text = "Paraguay" });
            CountryCodeList.Add(new SelectListItem { Value = "QA", Text = "Qatar" });
            CountryCodeList.Add(new SelectListItem { Value = "RE", Text = "Reunion" });
            CountryCodeList.Add(new SelectListItem { Value = "RO", Text = "Romania" });
            CountryCodeList.Add(new SelectListItem { Value = "RU", Text = "Russian Federation" });
            CountryCodeList.Add(new SelectListItem { Value = "RW", Text = "Rwanda" });
            CountryCodeList.Add(new SelectListItem { Value = "SA", Text = "Saudi Arabia" });
            CountryCodeList.Add(new SelectListItem { Value = "SB", Text = "Solomon Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "SC", Text = "Seychelles" });
            CountryCodeList.Add(new SelectListItem { Value = "SD", Text = "Sudan" });
            CountryCodeList.Add(new SelectListItem { Value = "SE", Text = "Sweden" });
            CountryCodeList.Add(new SelectListItem { Value = "SG", Text = "Singapore" });
            CountryCodeList.Add(new SelectListItem { Value = "SH", Text = "Saint Helena" });
            CountryCodeList.Add(new SelectListItem { Value = "SI", Text = "Slovenia" });
            CountryCodeList.Add(new SelectListItem { Value = "SJ", Text = "Svalbard and Jan Mayen" });
            CountryCodeList.Add(new SelectListItem { Value = "SK", Text = "Slovakia" });
            CountryCodeList.Add(new SelectListItem { Value = "SL", Text = "Sierra Leone" });
            CountryCodeList.Add(new SelectListItem { Value = "SM", Text = "San Marino" });
            CountryCodeList.Add(new SelectListItem { Value = "SN", Text = "Senegal" });
            CountryCodeList.Add(new SelectListItem { Value = "SO", Text = "Somalia" });
            CountryCodeList.Add(new SelectListItem { Value = "SR", Text = "Suriname" });
            CountryCodeList.Add(new SelectListItem { Value = "ST", Text = "Sao Tome and Principe" });
            CountryCodeList.Add(new SelectListItem { Value = "SU", Text = "USSR (former)" });
            CountryCodeList.Add(new SelectListItem { Value = "SV", Text = "El Salvador" });
            CountryCodeList.Add(new SelectListItem { Value = "SY", Text = "Syria" });
            CountryCodeList.Add(new SelectListItem { Value = "SZ", Text = "Swaziland" });
            CountryCodeList.Add(new SelectListItem { Value = "TC", Text = "Turks and Caicos Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "TD", Text = "Chad" });
            CountryCodeList.Add(new SelectListItem { Value = "TF", Text = "French Southern Territories" });
            CountryCodeList.Add(new SelectListItem { Value = "TG", Text = "Togo" });
            CountryCodeList.Add(new SelectListItem { Value = "TH", Text = "Thailand" });
            CountryCodeList.Add(new SelectListItem { Value = "TJ", Text = "Tajikistan" });
            CountryCodeList.Add(new SelectListItem { Value = "TK", Text = "Tokelau" });
            CountryCodeList.Add(new SelectListItem { Value = "TL", Text = "Timor-Leste" });
            CountryCodeList.Add(new SelectListItem { Value = "TM", Text = "Turkmenistan" });
            CountryCodeList.Add(new SelectListItem { Value = "TN", Text = "Tunisia" });
            CountryCodeList.Add(new SelectListItem { Value = "TO", Text = "Tonga" });
            CountryCodeList.Add(new SelectListItem { Value = "TP", Text = "East Timor" });
            CountryCodeList.Add(new SelectListItem { Value = "TR", Text = "Turkey" });
            CountryCodeList.Add(new SelectListItem { Value = "TT", Text = "Trinidad and Tobago" });
            CountryCodeList.Add(new SelectListItem { Value = "TV", Text = "Tuvalu" });
            CountryCodeList.Add(new SelectListItem { Value = "TW", Text = "Taiwan" });
            CountryCodeList.Add(new SelectListItem { Value = "TZ", Text = "Tanzania" });
            CountryCodeList.Add(new SelectListItem { Value = "UA", Text = "Ukraine" });
            CountryCodeList.Add(new SelectListItem { Value = "UG", Text = "Uganda" });
            CountryCodeList.Add(new SelectListItem { Value = "UK", Text = "United Kingdom" });
            CountryCodeList.Add(new SelectListItem { Value = "UM", Text = "United States Minor Outlying Islands" });
            CountryCodeList.Add(new SelectListItem { Value = "US", Text = "United States"});
            CountryCodeList.Add(new SelectListItem { Value = "UY", Text = "Uruguay" });
            CountryCodeList.Add(new SelectListItem { Value = "UZ", Text = "Uzbekistan" });
            CountryCodeList.Add(new SelectListItem { Value = "VA", Text = "Vatican City State (Holy See)" });
            CountryCodeList.Add(new SelectListItem { Value = "VC", Text = "Saint Vincent and the Grenadines" });
            CountryCodeList.Add(new SelectListItem { Value = "VE", Text = "Venezuela" });
            CountryCodeList.Add(new SelectListItem { Value = "VG", Text = "Virgin Islands (British)" });
            CountryCodeList.Add(new SelectListItem { Value = "VI", Text = "Virgin Islands (U.S.)" });
            CountryCodeList.Add(new SelectListItem { Value = "VN", Text = "Viet Nam" });
            CountryCodeList.Add(new SelectListItem { Value = "VU", Text = "Vanuatu" });
            CountryCodeList.Add(new SelectListItem { Value = "WF", Text = "Wallis and Futuna" });
            CountryCodeList.Add(new SelectListItem { Value = "WS", Text = "Samoa" });
            CountryCodeList.Add(new SelectListItem { Value = "YE", Text = "Yemen" });
            CountryCodeList.Add(new SelectListItem { Value = "YT", Text = "Mayotte" });
            CountryCodeList.Add(new SelectListItem { Value = "YU", Text = "Yugoslavia (former)" });
            CountryCodeList.Add(new SelectListItem { Value = "ZA", Text = "South Africa" });
            CountryCodeList.Add(new SelectListItem { Value = "ZM", Text = "Zambia" });
            CountryCodeList.Add(new SelectListItem { Value = "ZR", Text = "Zaire (former)" });
            CountryCodeList.Add(new SelectListItem { Value = "ZW", Text = "Zimbabwe" });
        }
    }
}