#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.Organization.Views.Dashboard
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Organization/Views/Dashboard/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.Entities.Organization>
    {
        public Index()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
  
    ViewBag.Title = "University Dashboard";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideBar", () => {

WriteLiteral("\r\n");


            
            #line 8 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
      Html.RenderAction(MVC.Home.SidebarDisplay(MyJobLeads.Controllers.ActiveSidebarLink.OrgAdmin));

            
            #line default
            #line hidden

});

WriteLiteral("\r\n\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"pageInfoBox\">         \r\n     " +
"   <div class=\"grid3 marginBottom_10 marginAuto floatLeft\"> \r\n            <h3 cl" +
"ass=\"floatLeft\">University Dashboard</h3> \r\n            ");


            
            #line 15 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
       Write(Html.ActionLink("Edit University Options", MVC.Organization.EditOrganization.Index(Model.Id), new { @class = "floatRight blueLinks", title = "Edit University Options" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div> \r\n                \r\n        <div class=\"grid3 marginBottom_10 fl" +
"oatLeft\"> \r\n            <div class=\"floatLeft\"><p class=\"greyHighlight\">Universi" +
"ty Name:</p>\r\n                <div class=\"infoSpan\">");


            
            #line 20 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                 Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div> \r\n        </div> \r\n\r\n        <div class=\"grid3 marginB" +
"ottom_10 floatLeft\"> \r\n            <div class=\"floatLeft\"><p class=\"greyHighligh" +
"t\">Number of Students with an Account in MyLeads:</p>\r\n                <div clas" +
"s=\"infoSpan\">");


            
            #line 26 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                 Write(Model.Members.Count);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
            </div> 
        </div> 

        <div class=""grid3 marginBottom_10 floatLeft""> 
            <div class=""floatLeft""><p class=""greyHighlight"">Registration URL for Students:</p>
                <div class=""infoSpan"">
                    ");


            
            #line 33 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
               Write(Html.ActionLink(Url.Action("RegisterWithOrganization", "Account", new { area = "", registrationToke = Model.RegistrationToken }),
                        MVC.Account.RegisterWithOrganization(Model.RegistrationToken), new { @class = "inlineBlue" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div> \r\n        </div> \r\n\r\n");


            
            #line 39 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
         if (Model.IsEmailDomainRestricted)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\">\r\n                    <p class=\"greyHighlight\">Students must r" +
"egister with an email from the <span class=\"greyHighlight\">");


WriteLiteral("@");


            
            #line 43 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                                                                    Write(Model.EmailDomains.First().Domain);

            
            #line default
            #line hidden
WriteLiteral("</span> domain</p>\r\n                </div> \r\n            </div>\r\n");


            
            #line 46 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
        }

        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""grid3 marginBottom_10 floatLeft""> 
                <div class=""floatLeft""><p class=""greyHighlight""></p>
                    <div class=""infoSpan"">Students can register with any email address</div>
                </div> 
            </div>
");


            
            #line 55 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div> \r\n    </div> \r\n</div> ");


        }
    }
}
#pragma warning restore 1591
