#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.Organization.Views.Dashboard
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Organization/Views/Dashboard/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.Entities.Organization>
    {
        public Index()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
  
    ViewBag.Title = "Index";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>University Dashboard</h2>\r\n\r\n<p>\r\n    Name: ");


            
            #line 10 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
     Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n    Number of users: ");


            
            #line 11 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
                Write(Model.Members.Count);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n    Registration URL: \r\n        ");


            
            #line 13 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
   Write(Html.ActionLink("Registration URL", MVC.Account.RegisterWithOrganization((Guid?)Model.RegistrationToken)));

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n\r\n");


            
            #line 15 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
     if (Model.IsEmailDomainRestricted)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("User registration <b>IS</b> restricted by the following email domains:\r\n");



WriteLiteral("        <ul>\r\n");


            
            #line 19 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
             foreach (var email in Model.EmailDomains)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>");


            
            #line 21 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
               Write(email.Domain);

            
            #line default
            #line hidden
WriteLiteral("</li>   \r\n");


            
            #line 22 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");


            
            #line 24 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
    }

    else
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("User registration is <b>NOT</b> restricted by email domains <br />\r\n");


            
            #line 29 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");


            
            #line 32 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Areas\Organization\Views\Dashboard\Index.cshtml"
Write(Html.ActionLink("Edit Settings", MVC.Organization.EditOrganization.Index(Model.Id)));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
