#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.Organization.Views.Dashboard
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Organization/Views/Dashboard/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.ViewModels.Organizations.OrganizationDashboardViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
  
    ViewBag.Title = "University Dashboard";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideBar", () => {

WriteLiteral("\r\n");


            
            #line 8 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
      Html.RenderAction(MVC.Home.SidebarDisplay(MyJobLeads.Controllers.ActiveSidebarLink.OrgAdmin));

            
            #line default
            #line hidden

});

WriteLiteral("\r\n\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"pageInfoBox\">         \r\n     " +
"   <div class=\"grid3 marginBottom_10 marginAuto floatLeft\"> \r\n            <h3 cl" +
"ass=\"floatLeft\">University Dashboard</h3> \r\n            ");


            
            #line 15 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
       Write(Html.ActionLink("Edit University Options", MVC.Organization.EditOrganization.Index(Model.Organization.Id), new { @class = "floatRight blueLinks", title = "Edit University Options" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 16 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
       Write(Html.ActionLink("View Milestones", MVC.Organization.Milestone.List(), new { @class = "floatRight blueLinks", title = "View Milestones" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 17 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
       Write(Html.ActionLink("View Student Statistics", MVC.Organization.MemberStats.Index(Model.Organization.Id),
                                                 new { @class = "floatRight blueLinks", title = "Detailed Student Statistics" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <br />\r\n");


            
            #line 20 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
             if (Model.IsInFillPerfectPilot)
            {
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
           Write(Html.ActionLink("FillPerfect Pilot", MVC.FillPerfect.OrgPilotDashboard.Index(), new { @class = "floatRight blueLinks", title = "View FillPerfect Pilot Dashboard" }));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                                                                                                                                     
            }

            
            #line default
            #line hidden
WriteLiteral("        </div> \r\n                \r\n        <div class=\"grid3 marginBottom_10 floa" +
"tLeft\"> \r\n            <div class=\"floatLeft\"><p class=\"greyHighlight\">University" +
" Name:</p>\r\n                <div class=\"infoSpan\">");


            
            #line 28 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                 Write(Model.Organization.Name);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
            </div> 
        </div> 

        <div class=""grid3 marginBottom_10 floatLeft""> 
            <div class=""floatLeft""><p class=""greyHighlight"">Student Usage Summary:</p>
                <div class=""infoSpan"">
                    Number of registered students: <span class=""bold"">");


            
            #line 35 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                 Write(Model.NumMembers);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of entered companies: <span class=\"bol" +
"d\">");


            
            #line 36 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                               Write(Model.NumCompanies);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of entered contacts: <span class=\"bold" +
"\">");


            
            #line 37 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                              Write(Model.NumContacts);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of positions students have applied to:" +
" <span class=\"bold\">");


            
            #line 38 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                                Write(Model.NumAppliedPositions);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of positions students have not applied" +
" to: <span class=\"bold\">");


            
            #line 39 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                                    Write(Model.NumNotAppliedPositions);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of scheduled phone interviews: <span c" +
"lass=\"bold\">");


            
            #line 40 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                        Write(Model.NumOpenPhoneTasks);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of completed phone interviews: <span c" +
"lass=\"bold\">");


            
            #line 41 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                        Write(Model.NumClosedPhoneTasks);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of scheduled in-person interviews: <sp" +
"an class=\"bold\">");


            
            #line 42 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                            Write(Model.NumOpenInterviewTasks);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n                    Number of completed in-person interviews: <sp" +
"an class=\"bold\">");


            
            #line 43 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                            Write(Model.NumClosedInterviewTasks);

            
            #line default
            #line hidden
WriteLiteral(@"</span> <br />
                </div>
            </div> 
        </div> 

        <div class=""grid3 marginBottom_10 floatLeft""> 
            <div class=""floatLeft""><p class=""greyHighlight"">Registration URL for Students:</p>
                <div class=""infoSpan"">
                    ");


            
            #line 51 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
               Write(Html.ActionLink(Url.Action("RegisterWithOrganization", "Account", new { area = "", registrationToke = Model.Organization.RegistrationToken }),
                        MVC.Account.RegisterWithOrganization(Model.Organization.RegistrationToken), new { @class = "inlineBlue" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div> \r\n        </div> \r\n\r\n");


            
            #line 57 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
         if (Model.Organization.IsEmailDomainRestricted)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\">\r\n                    <p class=\"greyHighlight\">Students must r" +
"egister with an email from the <span class=\"greyHighlight\">");


WriteLiteral("@");


            
            #line 61 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                                                                    Write(Model.Organization.EmailDomains.First().Domain);

            
            #line default
            #line hidden
WriteLiteral("</span> domain</p>\r\n                </div> \r\n            </div>\r\n");


            
            #line 64 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
        }

        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""grid3 marginBottom_10 floatLeft""> 
                <div class=""floatLeft""><p class=""greyHighlight""></p>
                    <div class=""infoSpan"">Students can register with any email address</div>
                </div> 
            </div>
");


            
            #line 73 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 75 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
         if (Model.NonMemberOfficialDocuments.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""grid3 marginBottom_10 floatLeft"">
                <div class=""floatLeft"">
                    <p class=""greyHighlight"">Documentation For Career Services (not visible to students):</p>
                    <div class=""infoSpan"">
                        <ul>
");


            
            #line 82 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                             foreach (var doc in Model.NonMemberOfficialDocuments)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a href=\"");


            
            #line 84 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                        Write(doc.DownloadUrl);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"inlineBlue\">");


            
            #line 84 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                             Write(doc.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 85 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n                </div>" +
"\r\n            </div>\r\n");


            
            #line 90 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        \r\n        <div class=\"grid3 marginBottom_10 floatLeft\">\r\n            <div" +
" class=\"floatLeft\">\r\n                <p class=\"greyHighlight\">Documentation Visi" +
"ble To Students:</p>\r\n                <div class=\"infoSpan\">\r\n                  " +
"  <ul>\r\n\r\n");


            
            #line 98 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                         if (Model.Organization.MemberOfficialDocuments.Count > 0)
                        {
                            foreach (var doc in Model.Organization.MemberOfficialDocuments)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a href" +
"=\"");


            
            #line 103 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                        Write(doc.DownloadUrl);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"inlineBlue\">");


            
            #line 103 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                             Write(doc.Name);

            
            #line default
            #line hidden
WriteLiteral("</a> - \r\n                                    [ ");


            
            #line 104 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                 Write(Html.ActionLink("Hide From Students", MVC.Organization.Dashboard.HideDocumentFromMembers(doc.Id), new { @class = "inlineBlue" }));

            
            #line default
            #line hidden
WriteLiteral(" ]\r\n                                </li>\r\n");


            
            #line 106 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                            }
                        }

                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>No documentation has been selected to be visible " +
"students.</li>\r\n");


            
            #line 112 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral(@"
                    </ul>
                </div>
            </div>
        </div>

        <div class=""grid3 marginBottom_10 floatLeft"">
            <div class=""floatLeft"">
                <p class=""greyHighlight"">Documentation NOT Visible To Students:</p>
                <div class=""infoSpan"">
                    <ul>

");


            
            #line 125 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                         if (Model.HiddenMemberDocuments.Count > 0)
                        {
                            foreach (var doc in Model.HiddenMemberDocuments)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a href" +
"=\"");


            
            #line 130 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                        Write(doc.DownloadUrl);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"inlineBlue\">");


            
            #line 130 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                                                             Write(doc.Name);

            
            #line default
            #line hidden
WriteLiteral("</a> - \r\n                                    [ ");


            
            #line 131 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                                 Write(Html.ActionLink("Show To Students", MVC.Organization.Dashboard.ShowDocumentToMembers(doc.Id), new { @class = "inlineBlue" }));

            
            #line default
            #line hidden
WriteLiteral(" ]\r\n                                </li>\r\n");


            
            #line 133 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                            }
                        }

                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>All documentation is visible to students</li>\r\n");


            
            #line 139 "..\..\Areas\Organization\Views\Dashboard\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ul>\r\n                </div>\r\n            </div>\r\n        " +
"</div>\r\n\r\n        <div class=\"clear\"></div> \r\n    </div> \r\n</div> ");


        }
    }
}
#pragma warning restore 1591
