#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/RegisterWithOrganization.cshtml")]
    public class RegisterWithOrganization : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Accounts.OrganizationRegistrationViewModel>
    {
        public RegisterWithOrganization()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
  
    ViewBag.Title = "RegisterWithOrganization";
    Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Create A New Account</h2>\r\n\r\n<p>\r\n    As a member of the <b>");


            
            #line 11 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
                     Write(Model.OrganizationName);

            
            #line default
            #line hidden
WriteLiteral("</b> you are entitled to a free account.\r\n</p>\r\n\r\n");


            
            #line 14 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
 if (Model.RestrictedEmailDomains.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        ");


            
            #line 17 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
   Write(Model.OrganizationName);

            
            #line default
            #line hidden
WriteLiteral(" only allows users to sign up with an email address belonging to the following do" +
"mains:\r\n        <ul>\r\n");


            
            #line 19 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
             foreach (string domain in Model.RestrictedEmailDomains)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>");


WriteLiteral("@");


            
            #line 21 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
                 Write(domain);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");


            
            #line 22 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </p>\r\n");


            
            #line 25 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script src=\"");


            
            #line 27 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
        Write(Url.Content("~/Scripts/jquery.validate.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n<script src=\"");


            
            #line 28 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
        Write(Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n\r\n");


            
            #line 30 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
Write(Html.ValidationSummary(true, "Account creation was unsuccessful. Please correct the errors and try again."));

            
            #line default
            #line hidden
            
            #line 31 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
                                                                                                                

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <fieldset>\r\n            <legend>Account Information</legend>\r\n" +
"\r\n            ");


            
            #line 36 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
       Write(Html.HiddenFor(x => x.OrganizationName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 37 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
       Write(Html.HiddenFor(x => x.MinPasswordLength));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 38 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
       Write(Html.HiddenFor(x => x.RegistrationToken));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            <div class=\"editor-label\">\r\n                ");


            
            #line 41 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


            
            #line 44 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.TextBoxFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 45 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.ValidationMessageFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");


            
            #line 49 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.LabelFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


            
            #line 52 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.PasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 53 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");


            
            #line 57 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.LabelFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


            
            #line 60 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.PasswordFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 61 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
           Write(Html.ValidationMessageFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <p>\r\n                <input type=\"submit\" val" +
"ue=\"Register\" />\r\n            </p>\r\n        </fieldset>\r\n    </div>\r\n");


            
            #line 69 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\RegisterWithOrganization.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
