#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ResetPasswordResult.cshtml")]
    public class ResetPasswordResult : System.Web.Mvc.WebViewPage<Boolean>
    {
        public ResetPasswordResult()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\ResetPasswordResult.cshtml"
  
    ViewBag.Title = "Password Reset";
    Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Password Reset</h2>\r\n");


            
            #line 9 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\ResetPasswordResult.cshtml"
 if (Model)
{

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        Password successfully reset.  You should receive an email notify" +
"ing you of your new password.\r\n    </p>\r\n");


            
            #line 14 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\ResetPasswordResult.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        No user has the email entered.  Please go back and verify the em" +
"ail entered is correct.\r\n    </p>\r\n");


            
            #line 20 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Account\ResetPasswordResult.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
