#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.ContactSearch.Views.Sync
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/ContactSearch/Views/Sync/Jigsaw.cshtml")]
    public class Jigsaw : System.Web.Mvc.WebViewPage<MyJobLeads.Areas.ContactSearch.Models.Sync.JigsawSyncViewModel>
    {
        public Jigsaw()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
  
    ViewBag.Title = "Contact Sync w/ Jigsaw";


            
            #line default
            #line hidden
WriteLiteral(@"
<div class=""grid1 floatLeft""> 
    <div class=""pageInfoBox"">
        <div class=""grid3 marginBottom_10 marginAuto floatLeft""> 
            <h3 class=""floatLeft"">Sync Contact With Imported Data</h3> 
        </div>

        <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
            <p>
                This page allows you to select what data you wish to import from the internet for this particular contact. <br />
                This contact's data was last updated in Jigsaw's database on ");


            
            #line 16 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                                                        Write(Model.LastUpdatedOnJigsaw.ToString("MM/dd/yyyy"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n        </div>\r\n        \r\n");


            
            #line 20 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
         using (Html.BeginForm())
        { 
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
       Write(Html.HiddenFor(x => x.ContactId));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                             
            
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
       Write(Html.HiddenFor(x => x.JigsawId));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                            
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
       Write(Html.HiddenFor(x => x.JigsawEmail));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                               
            
            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
       Write(Html.HiddenFor(x => x.JigsawName));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                              
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
       Write(Html.HiddenFor(x => x.JigsawPhone));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                               
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
       Write(Html.HiddenFor(x => x.JigsawTitle));

            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                               
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
       Write(Html.HiddenFor(x => x.LastUpdatedOnJigsaw));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                                       
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\">\r\n                <p>");


            
            #line 31 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
              Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n");


            
            #line 33 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""grid3 marginBottom_10 floatLeft""> 
                <table id=""SyncDataTable"" class=""display"">
                    <thead>
                        <th></th>
                        <th>Import?</th>
                        <th>MyLeads Data</th>
                        <th>Jigsaw Data</th>
                    </thead>

                    <tr>
                        <td>Name:</td>
                        <td>");


            
            #line 45 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Html.CheckBoxFor(x => x.ImportName));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");


            
            #line 46 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Model.InternalName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");


            
            #line 47 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Model.JigsawName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n\r\n                    <tr>\r\n                   " +
"     <td>Title:</td>\r\n                        <td>");


            
            #line 52 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Html.CheckBoxFor(x => x.ImportTitle));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");


            
            #line 53 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Model.InternalTitle);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");


            
            #line 54 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Model.JigsawTitle);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n\r\n                    <tr>\r\n                   " +
"     <td>Email:</td>\r\n                        <td>");


            
            #line 59 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Html.CheckBoxFor(x => x.ImportEmail));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");


            
            #line 60 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Model.InternalEmail);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>\r\n");


            
            #line 62 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                             if (string.IsNullOrWhiteSpace(Model.JigsawEmail))
                            {
                                
            
            #line default
            #line hidden
            
            #line 64 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                           Write(Html.ActionLink("Jigsaw Contact Purchase Required", MVC.ContactSearch.Jigsaw.PurchaseContact(Model.JigsawId, Model.JigsawName, Request.Url.PathAndQuery),
                                    new { @class = "inlineBlue", title = "Purchase contact from Jigsaw" }));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                                                                                          
                            }
                            
                            else { 
            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                              Write(Model.JigsawEmail);

            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                                      }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n                    </tr>\r\n\r\n                    <" +
"tr>\r\n                        <td>Phone:</td>\r\n                        <td>");


            
            #line 74 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Html.CheckBoxFor(x => x.ImportPhone));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");


            
            #line 75 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                       Write(Model.InternalPhone);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>\r\n");


            
            #line 77 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                             if (string.IsNullOrWhiteSpace(Model.JigsawPhone))
                            {
                                
            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                           Write(Html.ActionLink("Jigsaw Contact Purchase Required", MVC.ContactSearch.Jigsaw.PurchaseContact(Model.JigsawId, Model.JigsawName, Request.Url.PathAndQuery),
                                    new { @class = "inlineBlue", title = "Purchase contact from Jigsaw" }));

            
            #line default
            #line hidden
            
            #line 80 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                                                                                          
                            }

                            else
                            { 
            
            #line default
            #line hidden
            
            #line 84 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                         Write(Model.JigsawPhone);

            
            #line default
            #line hidden
            
            #line 84 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
                                                 }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n                    </tr>\r\n                </table" +
">\r\n            </div>\r\n");


            
            #line 89 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_20 floatLeft\"> \r\n                <br /" +
">\r\n                <div class=\"submitBTN \">\r\n                    <input type=\"su" +
"bmit\" value=\"Import Selected Data\" />\r\n                </div>\r\n            </div" +
"> \r\n");


            
            #line 96 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"clear\"></div>\r\n");


            
            #line 98 "..\..\Areas\ContactSearch\Views\Sync\Jigsaw.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
