// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyJobLeads.Areas.CompanySearch.Controllers {
    public partial class JigsawController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected JigsawController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PerformSearch() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PerformSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Details() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddCompany() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddCompany);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddCompanySuccess() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddCompanySuccess);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Sync() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Sync);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public JigsawController Actions { get { return MVC.CompanySearch.Jigsaw; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "CompanySearch";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Jigsaw";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string PerformSearch = "PerformSearch";
            public readonly string Details = "Details";
            public readonly string AddCompany = "AddCompany";
            public readonly string AddCompanySuccess = "AddCompanySuccess";
            public readonly string Sync = "Sync";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _SearchForm = "~/Areas/CompanySearch/Views/Jigsaw/_SearchForm.cshtml";
            public readonly string AddCompany = "~/Areas/CompanySearch/Views/Jigsaw/AddCompany.cshtml";
            public readonly string AddCompanySuccess = "~/Areas/CompanySearch/Views/Jigsaw/AddCompanySuccess.cshtml";
            public readonly string Details = "~/Areas/CompanySearch/Views/Jigsaw/Details.cshtml";
            public readonly string Index = "~/Areas/CompanySearch/Views/Jigsaw/Index.cshtml";
            public readonly string PerformSearch = "~/Areas/CompanySearch/Views/Jigsaw/PerformSearch.cshtml";
            public readonly string Sync = "~/Areas/CompanySearch/Views/Jigsaw/Sync.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_JigsawController: MyJobLeads.Areas.CompanySearch.Controllers.JigsawController {
        public T4MVC_JigsawController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PerformSearch(MyJobLeads.Areas.CompanySearch.Models.Jigsaw.CompanySearchQueryViewModel query) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PerformSearch);
            callInfo.RouteValueDictionary.Add("query", query);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details(int jigsawId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Details);
            callInfo.RouteValueDictionary.Add("jigsawId", jigsawId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCompany(int jigsawId, string companyName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCompany);
            callInfo.RouteValueDictionary.Add("jigsawId", jigsawId);
            callInfo.RouteValueDictionary.Add("companyName", companyName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCompany(MyJobLeads.Areas.CompanySearch.Models.Jigsaw.AddCompanyViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCompany);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCompanySuccess(int companyId, string companyName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCompanySuccess);
            callInfo.RouteValueDictionary.Add("companyId", companyId);
            callInfo.RouteValueDictionary.Add("companyName", companyName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Sync(int companyId, int jigsawId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Sync);
            callInfo.RouteValueDictionary.Add("companyId", companyId);
            callInfo.RouteValueDictionary.Add("jigsawId", jigsawId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
