// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyJobLeads.Areas.FillPerfect.Controllers {
    public partial class FeedbackController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FeedbackController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Student01() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Student01);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Student02() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Student02);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Student03() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Student03);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Student04() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Student04);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FeedbackController Actions { get { return MVC.FillPerfect.Feedback; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "FillPerfect";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Feedback";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string SurveyCompleted = "SurveyCompleted";
            public readonly string Student01 = "Student01";
            public readonly string Student02 = "Student02";
            public readonly string Student03 = "Student03";
            public readonly string Student04 = "Student04";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Student01 = "~/Areas/FillPerfect/Views/Feedback/Student01.cshtml";
            public readonly string Student02 = "~/Areas/FillPerfect/Views/Feedback/Student02.cshtml";
            public readonly string Student03 = "~/Areas/FillPerfect/Views/Feedback/Student03.cshtml";
            public readonly string Student04 = "~/Areas/FillPerfect/Views/Feedback/Student04.cshtml";
            public readonly string SurveyCompleted = "~/Areas/FillPerfect/Views/Feedback/SurveyCompleted.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_FeedbackController: MyJobLeads.Areas.FillPerfect.Controllers.FeedbackController {
        public T4MVC_FeedbackController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult SurveyCompleted(int surveysCompleted) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SurveyCompleted);
            callInfo.RouteValueDictionary.Add("surveysCompleted", surveysCompleted);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student01(string fpUserId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student01);
            callInfo.RouteValueDictionary.Add("fpUserId", fpUserId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student01(MyJobLeads.Areas.FillPerfect.Models.Surveys.StudentSurveyPost3ViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student01);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student02(string fpUserId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student02);
            callInfo.RouteValueDictionary.Add("fpUserId", fpUserId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student02(MyJobLeads.Areas.FillPerfect.Models.Surveys.StudentSurveyPost5ViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student02);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student03(string fpUserId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student03);
            callInfo.RouteValueDictionary.Add("fpUserId", fpUserId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student03(MyJobLeads.Areas.FillPerfect.Models.Surveys.StudentSurveyPost10ViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student03);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student04(string fpUserId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student04);
            callInfo.RouteValueDictionary.Add("fpUserId", fpUserId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Student04(MyJobLeads.Areas.FillPerfect.Models.Surveys.StudentSurveyPost2WeeksViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Student04);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
