// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyJobLeads.Controllers {
    public partial class TaskController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TaskController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddCompanyTask() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddCompanyTask);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddContactTask() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddContactTask);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult View() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.View);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TaskController Actions { get { return MVC.Task; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Task";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string AddCompanyTask = "AddCompanyTask";
            public readonly string AddContactTask = "AddContactTask";
            public readonly string Edit = "Edit";
            public readonly string View = "View";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Edit = "~/Views/Task/Edit.cshtml";
            public readonly string View = "~/Views/Task/View.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_TaskController: MyJobLeads.Controllers.TaskController {
        public T4MVC_TaskController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult AddCompanyTask(int companyId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCompanyTask);
            callInfo.RouteValueDictionary.Add("companyId", companyId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddContactTask(int contactId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddContactTask);
            callInfo.RouteValueDictionary.Add("contactId", contactId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(MyJobLeads.DomainModel.Entities.Task task, int companyId, int contactId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("task", task);
            callInfo.RouteValueDictionary.Add("companyId", companyId);
            callInfo.RouteValueDictionary.Add("contactId", contactId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult View(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.View);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
