#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Policies
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Policies/Privacy.cshtml")]
    public class Privacy : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Privacy()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Policies\Privacy.cshtml"
  
    ViewBag.Title = "Privacy Policy";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"pageInfoBox\"> \r\n        <div cl" +
"ass=\"grid3 marginBottom_10 marginAuto floatLeft\">\r\n            <h3>We Protect Yo" +
"ur Privacy</h3>\r\n        </div>\r\n\r\n        <div class=\"grid3 marginBottom_10 mar" +
"ginAuto floatLeft\">\r\n            <p>\r\n                <ul class=\"decoratedList\">" +
"\r\n                    <li class=\"marginBottom_10\">\r\n                        All " +
"information you upload / enter into the MyLeads system is not accessible to any " +
"other students. In \r\n                        addition, specific notes, contacts," +
" and contact details cannot be read or monitored by others, including \r\n        " +
"                the Career Services administrator.\r\n                    </li>\r\n\r" +
"\n                    <li class=\"marginBottom_10\">\r\n                        The o" +
"nly information provided to your Career Services administrator are metrics measu" +
"ring activity – the \r\n                        number of tasks that you completed" +
", the number of interviews, the number of contacts (not contact \r\n              " +
"          details), etc. This information is provided to help Career Services ai" +
"d you in your job search, by measuring \r\n                        your progress i" +
"n the job search. Metrics are only available to the Career Services administrato" +
"r – no \r\n                        With one click, MyLeads downloads your entire d" +
"atabase to your desktop, in Excel format.students or non-administrator accounts " +
"\r\n                        have access to any information about your account or a" +
"ctivity, \r\n                        including metrics.\r\n                    </li>" +
"\r\n\r\n                    <li>\r\n                        MyLeads and InterviewTools" +
" will not pass on your email address or personal information to third-parties, w" +
"ithout your permission. \r\n                        In addition, we do not allow o" +
"thers to solicit you, through our system. Your email and all information \r\n     " +
"                   provided during  registration remains private within MyLeads," +
" and is used to help manage your account. \r\n                    </li>\r\n\r\n       " +
"             <li>\r\n                        There are times that MyLeads will con" +
"nect to 3rd\r\n                        party services on your behalf, for example " +
"LinkedIn and \r\n                        Jigsaw. If you choose to take advantage o" +
"f these services, you must provide your login credentials.\r\n                    " +
"    MyLeads will never use this information for any purpose other than logging i" +
"nto the systems, and we will \r\n                        never use your accounts o" +
"n those services for any purpose other than what the system tells you.\r\n        " +
"            </li>\r\n                </ul>\r\n            </p>\r\n\r\n            <p>\r\n " +
"               If you have any questions about your data or security, please fee" +
"l free to contact us at \r\n                    <a class=\"inlineBlue\" href=\"mailto" +
":support@interviewtools.net\">support@interviewtools.net</a>\r\n            </p>\r\n " +
"       </div>\r\n            \r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</di" +
"v>\r\n");


        }
    }
}
#pragma warning restore 1591
