#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.ResearchCenter
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ResearchCenter/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\ResearchCenter\Index.cshtml"
  
    ViewBag.Title = "Research Center";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideBar", () => {

WriteLiteral("\r\n");


            
            #line 6 "..\..\Views\ResearchCenter\Index.cshtml"
      Html.RenderAction(MVC.Home.SidebarDisplay(MyJobLeads.Controllers.ActiveSidebarLink.ResearchCenter));

            
            #line default
            #line hidden

});

WriteLiteral(@"

<div class=""grid1 floatLeft""> 
    <div class=""pageInfoBox""> 
        <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
            <h3>MyLeads Research Center</h3>
        </div>

        <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
            <p>
                MyLeads provides resources to perform research to make your job search more successful
            </p>

            <p>
                <ul class=""decoratedList"">
                    <li>
                        ");


            
            #line 23 "..\..\Views\ResearchCenter\Index.cshtml"
                   Write(Html.ActionLink("Research Open Jobs", MVC.PositionSearch.LinkedIn.Index(), new { @class = "inlineBlue", title = "Find Open Jobs" }));

            
            #line default
            #line hidden
WriteLiteral(@"
                    </li>
                    <li><a href=""#"" class=""inlineBlue"">Research Companies</a> <span class=""bold"">(Coming Soon)</span></li>
                    <li><a href=""#"" class=""inlineBlue"">Research Contacts</a> <span class=""bold"">(Coming Soon)</span></li>
                </ul>
            </p>
        </div>
            
        <div class=""clear""></div>
    </div>
</div>
");


        }
    }
}
#pragma warning restore 1591
