#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Task
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
    using MyJobLeads.DomainModel.Entities;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Task/_OpenTaskSummary.cshtml")]
    public class _OpenTaskSummary : System.Web.Mvc.WebViewPage<IList<Task>>
    {
        public _OpenTaskSummary()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


            
            #line 4 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
  
    var openTasks = Model ?? new List<Task>();
    var undatedTasks = openTasks.Where(x => x.TaskDate == null || !x.TaskDate.HasValue).ToArray();
    var overDueTasks = openTasks.Where(x => x.TaskDate != null && x.TaskDate.Value.Date < DateTime.Today).ToArray();
    var todaysTasks = openTasks.Where(x => x.TaskDate != null && x.TaskDate.Value.Date == DateTime.Today).ToArray();
    var futureTasks = openTasks.Where(x => x.TaskDate != null && x.TaskDate.Value.Date > DateTime.Today).ToArray();


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Open Tasks</h2>\r\n\r\n");


            
            #line 14 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
 if (openTasks.Count == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("All tasks entered have been completed\r\n");


            
            #line 17 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("Below are tasks which have not been completed yet:<br /><br />");

WriteLiteral("\r\n");


            
            #line 21 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"

    if (undatedTasks.Length > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Undated Tasks</h2>\r\n");



WriteLiteral("        <ul>\r\n");


            
            #line 26 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
             foreach (Task task in undatedTasks)
            {

            
            #line default
            #line hidden

            
            #line 28 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
WriteLiteral("                <li>");

            
            #line default
            #line hidden
            
            #line 28 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
                       Html.RenderPartial(MVC.Task.Views._OpenTaskListItem, task); 
            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");



WriteLiteral("                <li>&nbsp;</li>\r\n");


            
            #line 30 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");


            
            #line 32 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
    }
            
    if (overDueTasks.Length > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Overdue Tasks</h2>\r\n");



WriteLiteral("        <ul>\r\n");


            
            #line 38 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
             foreach (Task task in overDueTasks)
            {

            
            #line default
            #line hidden

            
            #line 40 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
WriteLiteral("                <li>");

            
            #line default
            #line hidden
            
            #line 40 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
                       Html.RenderPartial(MVC.Task.Views._OpenTaskListItem, task); 
            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");



WriteLiteral("                <li>&nbsp;</li>\r\n");


            
            #line 42 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");


            
            #line 44 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
    }

    if (todaysTasks.Length > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Today\'s Tasks</h2>\r\n");



WriteLiteral("        <ul>\r\n");


            
            #line 50 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
             foreach (Task task in todaysTasks)
            {

            
            #line default
            #line hidden

            
            #line 52 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
WriteLiteral("                <li>");

            
            #line default
            #line hidden
            
            #line 52 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
                       Html.RenderPartial(MVC.Task.Views._OpenTaskListItem, task); 
            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");



WriteLiteral("                <li>&nbsp;</li>\r\n");


            
            #line 54 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");


            
            #line 56 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
    }

    if (futureTasks.Length > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>Future Tasks</h2>\r\n");



WriteLiteral("        <ul>\r\n");


            
            #line 62 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
             foreach (Task task in futureTasks)
            {

            
            #line default
            #line hidden

            
            #line 64 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
WriteLiteral("                <li>");

            
            #line default
            #line hidden
            
            #line 64 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
                       Html.RenderPartial(MVC.Task.Views._OpenTaskListItem, task); 
            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");



WriteLiteral("                <li>&nbsp;</li>\r\n");


            
            #line 66 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");


            
            #line 68 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Task\_OpenTaskSummary.cshtml"
    }
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
