#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Task
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Task\Future.cshtml"
    using MyJobLeads.Controllers;
    
    #line default
    #line hidden
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Task/Future.cshtml")]
    public class Future : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Tasks.TaskDashboardViewModel>
    {
        public Future()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


            
            #line 4 "..\..\Views\Task\Future.cshtml"
  
    ViewBag.Title = "Future Tasks";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideBar", () => {

WriteLiteral("\r\n");


            
            #line 9 "..\..\Views\Task\Future.cshtml"
      Html.RenderAction(MVC.Home.SidebarDisplay(ActiveSidebarLink.Tasks));

            
            #line default
            #line hidden

});

WriteLiteral("\r\n\r\n<div class=\"grid2 floatLeft\">\r\n    <div class=\"taskHeader\">\r\n        <h3>Futu" +
"re Tasks</h3>\r\n        <ul class=\"taskNotification\">\r\n            <li><a href=\"");


            
            #line 16 "..\..\Views\Task\Future.cshtml"
                    Write(Url.Action(MVC.Task.Overdue()));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Overdue Tasks\">Overdue: <span>(");


            
            #line 16 "..\..\Views\Task\Future.cshtml"
                                                                                           Write(Model.OverdueTasks.Count);

            
            #line default
            #line hidden
WriteLiteral(")</span></a></li>\r\n            <li><a href=\"");


            
            #line 17 "..\..\Views\Task\Future.cshtml"
                    Write(Url.Action(MVC.Task.Today()));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Today\'s Tasks\">Today: <span>(");


            
            #line 17 "..\..\Views\Task\Future.cshtml"
                                                                                       Write(Model.TodaysTasks.Count);

            
            #line default
            #line hidden
WriteLiteral(")</span></a></li>\r\n        </ul>       \r\n    </div>\r\n\r\n");


            
            #line 21 "..\..\Views\Task\Future.cshtml"
     if (Model.FutureTasks.Count == 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"taskName\" style=\"margin-left:20px\">You have no tasks due afte" +
"r today</div>\r\n");


            
            #line 24 "..\..\Views\Task\Future.cshtml"
    }

    else
    {
        Html.RenderPartial(MVC.Task.Views.TaskListControl, Model.FutureTasks);
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


            
            #line 32 "..\..\Views\Task\Future.cshtml"
 if (Model.CurrentMilestone != null)
{
    Html.RenderPartial(MVC.JobSearch.Views._JsMilestoneDisplay, Model);
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
