#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Task
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Task/TaskListControl.cshtml")]
    public class TaskListControl : System.Web.Mvc.WebViewPage<IList<MyJobLeads.DomainModel.Entities.Task>>
    {
        public TaskListControl()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div id=\"taskRole\">\r\n    <ul>\r\n");


            
            #line 5 "..\..\Views\Task\TaskListControl.cshtml"
         foreach (var task in Model)
        {
            string taskDescription;
                 
            // Create the description string
            if (task.Contact == null)
            {
                taskDescription = task.Company.Name;
            }
            else
            {
                taskDescription = string.Format("{0} -- {1}", task.Contact.Name, task.Company.Name);
            }
            

            
            #line default
            #line hidden
WriteLiteral("            <li>\r\n                <a href=\"");


            
            #line 20 "..\..\Views\Task\TaskListControl.cshtml"
                    Write(Url.Action(MVC.Task.Details(task.Id)));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <div class=\"greyHighlight date\">");


            
            #line 21 "..\..\Views\Task\TaskListControl.cshtml"
                                               Write(Html.GetDueDateString(task.TaskDate));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"taskName\">");


            
            #line 22 "..\..\Views\Task\TaskListControl.cshtml"
                                     Write(task.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"taskDescription\">");


            
            #line 23 "..\..\Views\Task\TaskListControl.cshtml"
                                            Write(taskDescription);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </a>\r\n            </li>\r\n");


            
            #line 26 "..\..\Views\Task\TaskListControl.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
