#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Contact
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Contact/_ContactSidebarDisplay.cshtml")]
    public class _ContactSidebarDisplay : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.Entities.Contact>
    {
        public _ContactSidebarDisplay()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<h2>");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n<span class=\"data-label\">Direct Phone:</span>\r\n<span class=\"data-value\">" +
"");


            
            #line 6 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                    Write(Model.DirectPhone);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\r\n");


            
            #line 8 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
 if (!string.IsNullOrWhiteSpace(Model.Extension))
{

            
            #line default
            #line hidden
WriteLiteral("    <span class=\"data-label\">Ext:</span>\r\n");



WriteLiteral("    <span class=\"data-value\">");


            
            #line 11 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                        Write(Model.Extension);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 12 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<br />\r\n\r\n<span class=\"data-label\">Mobile Phone:</span> <span class=\"data-value" +
"\">");


            
            #line 16 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                                                                  Write(Model.MobilePhone);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n<span class=\"data-label\">Email:</span> <a href=\"mailto:");


            
            #line 17 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                                                  Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 17 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                                                                Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("</a> <br />\r\n<span class=\"data-label\">Assistant:</span> <span class=\"data-value\">" +
"");


            
            #line 18 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                                                               Write(Model.Assistant);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n<span class=\"data-label\">Referred By:</span> <span class=\"data-va" +
"lue\">");


            
            #line 19 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                                                                 Write(Model.ReferredBy);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n\r\n<span class=\"data-label\">Notes:</span> \r\n<span class=\"data-valu" +
"e\">");


            
            #line 22 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
                    Write(Html.Raw(Html.Encode(Model.Notes).Replace(Environment.NewLine, "<br />")));

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n\r\n");


            
            #line 24 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\_ContactSidebarDisplay.cshtml"
Write(Html.ActionLink("Show Details", MVC.Contact.Details(Model.Id), new { @class = "details-link" }));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
