#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Contact
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Contact/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Contacts.ContactDisplayViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
  
    ViewBag.Title = "Contact: " + Model.Name;


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"lineSeperater\"> \r\n        <div " +
"class=\"pageInfoBox\">\r\n            <div class=\"grid3 marginBottom_10 marginAuto f" +
"loatLeft\"> \r\n                <h3 class=\"floatLeft\">Contact: ");


            
            #line 11 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                          Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3> \r\n                ");


            
            #line 12 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
           Write(Html.ActionLink("Edit Details", MVC.Contact.Edit(Model.Id), new { @class = "floatRight blueLinks", title = "Edit Details" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 13 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
           Write(Html.ActionLink("Add Task", MVC.Task.Add(Model.Company.Id, Model.Id), new { @class = "floatRight blueLinks", title = "Add task" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div> \r\n\r\n            <div class=\"grid3 marginBottom_10 floatLeft\"" +
"> \r\n                <div class=\"grid4 floatLeft\"> \r\n                    <p class" +
"=\"greyHighlight\">Title: <span class=\"setTask\">");


            
            #line 18 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                                                     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></p> \r\n                    <p class=\"greyHighlight\">Email: <span class=\"se" +
"tTask\">");


            
            #line 19 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                                                     Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("</span></p> \r\n                    <p class=\"greyHighlight\">Assistant: <span class" +
"=\"setTask\">");


            
            #line 20 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                                                         Write(Model.Assistant);

            
            #line default
            #line hidden
WriteLiteral("</span></p> \r\n                    <p class=\"greyHighlight\">Referred By: <span cla" +
"ss=\"setTask\">");


            
            #line 21 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                                                           Write(Model.ReferredBy);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n                </div> \r\n\r\n                <div class=\"grid4 floatRi" +
"ght\"> \r\n                    <p class=\"greyHighlight\">Direct Phone: <span class=\"" +
"setTask\">");


            
            #line 25 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                                                            Write(Model.DirectPhoneWithExtension);

            
            #line default
            #line hidden
WriteLiteral("</span></p> \r\n                    <p class=\"greyHighlight\">Mobile Phone: <span cl" +
"ass=\"setTask\">");


            
            #line 26 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                                                            Write(Model.MobilePhone);

            
            #line default
            #line hidden
WriteLiteral(@"</span></p> 
                </div> 
            </div> 
                                
            <div class=""grid3 marginBottom_10 floatLeft""> 
                <div class=""floatLeft"">
                    <p class=""greyHighlight"">Notes: 
                        <span class=""setTask"">");


            
            #line 33 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
                                         Write(Html.Raw(Html.Encode(Model.Notes).Replace(Environment.NewLine, "<br />")));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </p>\r\n                </div> \r\n            </div> \r\n" +
"\r\n            <div class=\"clear\"></div>\r\n        </div> \r\n    </div> \r\n</div>\r\n\r" +
"\n");


            
            #line 43 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Contact\Details.cshtml"
  Html.RenderPartial(MVC.Company.Views._CompanySummaryDisplay, Model.Company);
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
