using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyJobLeads.Areas.Admin.Models.DemoAccountCreation
{
    public class DemoCreationValues
    {
        #region Companies
        public List<List<string>> Companies = new List<List<string>>
        {
            new List<string> { "Wal-Mart Stores",	"(602) 469-6053",	"Chicago",	"IL",	"21756",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Exxon Mobil",	"(602) 108-9373",	"New York City",	"NY",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Chevron",	"(202) 228-8243",	"Minneapolis ",	"MN",	"21756",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "General Electric",	"(967) 716-9743",	"Minneapolis ",	"MN",	"21756",	"Prospective Employer",	"Large firm, world-provider of loans and credit." },
            new List<string> { "Bank of America Corp.",	"(671) 918-6634",	"New York City",	"NY",	"20587",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "ConocoPhillips",	"(902) 755-3972",	"New York City",	"NY",	"21756",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "AT&T",	"(602) 744-3099",	"Minneapolis ",	"MN",	"58795",	"Prospective Employer",	"AT&T Corp. is a business services communications provider, offering a variety of global communications services to over two-million customers, including large domestic and multinational businesses, small and medium-sized businesses and government agencies.     Revenue: $23 billion  " },
            new List<string> { "Ford Motor",	"(212) 192-4756",	"New York City",	"NY",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "J.P. Morgan Chase & Co.",	"(202) 536-3897",	"San Francisco",	"CA",	"20587",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Hewlett-Packard",	"(902) 370-5443",	"Seattle",	"WA",	"20587",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Berkshire Hathaway",	"(967) 170-9767",	"Los Angeles",	"CA",	"27985",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Citigroup",	"(902) 286-7718",	"Williamsburg",	"VA",	"27985",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Verizon Communications",	"(212) 379-2276",	"Minneapolis ",	"MN",	"36498",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "McKesson",	"(212) 227-1816",	"Seattle",	"WA",	"58795",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "General Motors",	"(902) 941-7646",	"Williamsburg",	"VA",	"20587",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "American International Group",	"(212) 636-5594",	"Los Angeles",	"CA",	"36498",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Cardinal Health",	"(202) 954-6469",	"Los Angeles",	"CA",	"27985",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "CVS Caremark",	"(202) 333-4990",	"Williamsburg",	"VA",	"58795",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Wells Fargo",	"(602) 808-8149",	"Minneapolis ",	"MN",	"58795",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "International Business Machines",	"(212) 247-6473",	"Williamsburg",	"VA",	"21756",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "UnitedHealth Group",	"(602) 566-2769",	"Los Angeles",	"CA",	"27985",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Procter & Gamble",	"(902) 092-4288",	"New York City",	"NY",	"20587",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Kroger",	"(967) 236-3963",	"Minneapolis ",	"MN",	"17652",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "AmerisourceBergen",	"(967) 168-7118",	"Atlanta ",	"GA",	"36498",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Costco Wholesale",	"(602) 780-4595",	"San Francisco",	"CA",	"58795",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Valero Energy",	"(671) 566-6787",	"Williamsburg",	"VA",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Archer Daniels Midland",	"(202) 919-6636",	"Chicago",	"IL",	"21756",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Boeing",	"(671) 094-1724",	"New York City",	"NY",	"21756",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Home Depot",	"(967) 269-1772",	"Seattle",	"WA",	"17652",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Target",	"(671) 211-1291",	"Seattle",	"WA",	"20587",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "WellPoint",	"(967) 893-4510",	"New York City",	"NY",	"36498",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Walgreen",	"(202) 210-6333",	"Williamsburg",	"VA",	"17652",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Johnson & Johnson",	"(671) 729-4497",	"Chicago",	"IL",	"21756",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments.    Testing" },
            new List<string> { "State Farm Insurance Cos.",	"(602) 862-3486",	"Los Angeles",	"CA",	"27985",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Medco Health Solutions",	"(212) 571-3986",	"Minneapolis ",	"MN",	"27985",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Microsoft",	"(212) 364-5834",	"Seattle",	"WA",	"21756",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "United Technologies",	"(202) 583-2203",	"Atlanta ",	"GA",	"21756",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Dell",	"(602) 162-7066",	"Atlanta ",	"GA",	"21756",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Goldman Sachs Group",	"(212) 398-5121",	"San Francisco",	"CA",	"21756",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Pfizer",	"(671) 638-0129",	"Williamsburg",	"VA",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Marathon Oil",	"(967) 307-5077",	"San Francisco",	"CA",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Lowe's",	"(902) 295-9505",	"Minneapolis ",	"MN",	"20587",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "United Parcel Service",	"(902) 957-5793",	"Los Angeles",	"CA",	"36498",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Lockheed Martin",	"(602) 758-9039",	"Chicago",	"IL",	"58795",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Best Buy",	"(202) 651-1209",	"Williamsburg",	"VA",	"21756",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Dow Chemical",	"(212) 863-0672",	"Atlanta ",	"GA",	"20587",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Supervalue",	"(967) 251-3949",	"Seattle",	"WA",	"58795",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Sears Holdings",	"(212) 396-2534",	"San Francisco",	"CA",	"17652",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "International Assets Holding",	"(212) 271-5505",	"San Francisco",	"CA",	"27985",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "PepsiCo",	"(967) 108-4128",	"Williamsburg",	"VA",	"21756",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "MetLife",	"(902) 492-7067",	"Atlanta ",	"GA",	"27985",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Safeway",	"(902) 456-0949",	"Chicago",	"IL",	"27985",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Kraft Foods",	"(202) 374-7809",	"Williamsburg",	"VA",	"36498",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Freddie Mac",	"(202) 845-5351",	"Williamsburg",	"VA",	"17652",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Sysco",	"(212) 038-8713",	"Minneapolis ",	"MN",	"20587",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Apple",	"(902) 382-4852",	"San Francisco",	"CA",	"17652",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Walt Disney",	"(202) 139-9447",	"Minneapolis ",	"MN",	"58795",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Cisco Systems",	"(202) 330-8217",	"Chicago",	"IL",	"20587",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Comcast",	"(212) 858-3892",	"Los Angeles",	"CA",	"27985",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "FedEx",	"(602) 534-3485",	"Williamsburg",	"VA",	"17652",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Northrop Grumman",	"(212) 711-2841",	"New York City",	"NY",	"21756",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Intel",	"(671) 696-1332",	"San Francisco",	"CA",	"21756",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Aetna",	"(602) 473-3985",	"Williamsburg",	"VA",	"21756",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "New York Life Insurance",	"(602) 323-0952",	"Atlanta ",	"GA",	"21756",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Prudential Financial",	"(967) 901-3501",	"Seattle",	"WA",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Caterpillar",	"(902) 921-9599",	"Minneapolis ",	"MN",	"17652",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Sprint Nextel",	"(212) 774-4625",	"Williamsburg",	"VA",	"21756",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Allstate",	"(602) 547-1268",	"Minneapolis ",	"MN",	"27985",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "General Dynamics",	"(902) 025-3438",	"Atlanta ",	"GA",	"58795",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Morgan Stanley",	"(212) 093-8439",	"Chicago",	"IL",	"27985",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Coca-Cola",	"(967) 365-2389",	"Minneapolis ",	"MN",	"17652",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Humana",	"(212) 850-7645",	"Williamsburg",	"VA",	"58795",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "Honeywell International",	"(202) 376-8052",	"New York City",	"NY",	"58795",	"Prospective Employer",	"Worldwide sales of edible widgets and banana rings." },
            new List<string> { "Abbott Laboratories",	"(202) 689-1679",	"Seattle",	"WA",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "News Corp.",	"(212) 896-1094",	"Atlanta ",	"GA",	"36498",	"Prospective Employer",	"Manufacturer of mouse pads and light bulbs filaments." },
            new List<string> { "HCA",	"(212) 300-5078",	"Williamsburg",	"VA",	"36498",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Sunoco",	"(212) 573-3182",	"San Francisco",	"CA",	"36498",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Hess",	"(602) 145-9487",	"Atlanta ",	"GA",	"17652",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Ingram Micro",	"(671) 832-2994",	"Williamsburg",	"VA",	"17652",	"Prospective Employer",	"Software - complete machine vision systems, vision sensors, ID readers, and web/surface inspection systems" },
            new List<string> { "Fannie Mae",	"(967) 071-3736",	"Williamsburg",	"VA",	"20587",	"Prospective Employer",	"Large bank, world-provider of loans and credit." },
            new List<string> { "Demo",	"101-202-2020",	"Denver",	"CO",	"80217",	"Prospective Employer",	"N/Q" },
            new List<string> { "George H Dean Co.",	"+1.781.356.4100",	"Braintree",	"MA",	"02184-5239",	"Prospective Employer",	"" }
        };
        #endregion

        #region Contacts
        public List<List<string>> Contacts = new List<List<string>>
        {
            new List<string> { "Josh Stark",	"(602) 972-5291",	"(602) 040-0821",	"3030",	"Josh.Stark@walmart.com",	"Jim Smith",	"Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Irene Nelson",	"(902) 386-7416",	"(902) 284-8896",	"4994",	"Irene.Nelson@exxon.com",	"Jeff Voss",	"Former Classmate",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Richard Smith",	"(967) 501-3942",	"",	"9836",	"Richard.Smith@cheveron.com",	"Padma Perry",	"Colleague",	"3/1 Applied online using this person's name." },
            new List<string> { "Jim Wick",	"(671) 713-6046",	"(671) 314-7658",	"3721",	"Jim.Wick@ge.com",	"Nate Stein",	"Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Josh Perry",	"(202) 103-4043",	"(202) 856-5465",	"4058",	"Josh.Perry@bofa.com",	"Michael  Stein",	"Hoovers' Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Nate Hewitt",	"(671) 482-4591",	"",	"9870",	"Nate.Hewitt@conoco.com",	" ",	"Website",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Nate Rudolph",	"(202) 756-7446",	"(202) 651-2994",	"6725",	"Nate.Rudolph@att.com",	"Anna Robinson",	"Former Classmate",	"3/1 Applied online using this person's name.    2/18 Spoke to Nate. He asked me to apply online and use his name on the application." },
            new List<string> { "Jim Rudolph",	"(902) 384-7186",	"(902) 025-3706",	"8786",	"Jim.Rudolph@ford.com",	"Padma Cohen",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Matt Cohen",	"(902) 119-4733",	"(902) 879-5514",	"9012",	"Matt.Cohen@jpmorgan.com",	"Jim Wick",	"Recpetionist",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Rick Shapiro",	"(212) 378-7119",	"(212) 667-6767",	"2115",	"Rick.Shapiro@hp.com",	"Debbie Stark",	"Former Classmate",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Irene Wick",	"(202) 689-3052",	"(202) 900-8968",	"3978",	"Irene.Wick@berkshire.com",	"Matt Nelson",	"Colleague",	"3/1 Applied online using this person's name." },
            new List<string> { "Irene Stein",	"(202) 881-6797",	"",	"1625",	"Irene.Stein@citi.com",	" ",	"Former Classmate",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Peter Stein",	"(671) 399-7950",	"(671) 225-0226",	"2197",	"Peter.Stein@verizon.com",	" ",	"Linked-In",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Al McAveeney",	"(202) 945-4591",	"(202) 241-3110",	"2534",	"Al.McAveeney@mckesson.com",	"Jim Thornton",	"Hoovers' Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Barry Voss",	"(902) 149-6732",	"(902) 204-0286",	"5414",	"Barry.Voss@gm.com",	"Rick Wick",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Nate Stein",	"(212) 446-3067",	"",	"1659",	"Nate.Stein@aig.com",	" ",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Richard Cohen",	"(967) 591-1842",	"(967) 163-1455",	"1666",	"Richard.Cohen@cardinal.com",	"Rhonda Stein",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Louise Nelson",	"(212) 734-0901",	"(212) 594-3184",	"9512",	"Louise.Nelson@cvs.com",	"Irene Stein",	"Website",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Jill Perry",	"(212) 805-4001",	"",	"1007",	"Jill.Perry@wellsfargo.com",	"Peter Smith",	"Linked-In",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Rick Rudolph",	"(202) 339-4774",	"",	"2985",	"Rick.Rudolph@ibm.com",	"Jeff Thornton",	"Recpetionist",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Irene Jacobs",	"(902) 829-0448",	"(902) 042-3178",	"5537",	"Irene.Jacobs@uhg.com",	" ",	"Former Classmate",	"3/1 Applied online using this person's name." },
            new List<string> { "Rick Stein",	"(967) 646-6331",	"(967) 535-1326",	"6346",	"Rick.Stein@pg.com",	" ",	"Colleague",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Irene Thornton",	"(202) 188-8201",	"",	"6172",	"Irene.Thornton@kroger.com",	" ",	"Linked-In",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Nate Stark",	"(602) 487-7183",	"",	"8077",	"Nate.Stark@amerisource.com",	"Padma Jacobs",	"Colleague",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jack Hewitt",	"(902) 118-3466",	"",	"9510",	"Jack.Hewitt@costco.com",	"Irene Nelson",	"Former Classmate",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Barry Nelson",	"(212) 027-1413",	"(212) 598-3882",	"8729",	"Barry.Nelson@valero.com",	"Al Jacobs",	"Website",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Theresa Jacobs",	"(967) 086-7479",	"",	"2582",	"Theresa.Jacobs@adm.com",	"Michael  Voss",	"Hoovers' Website",	"3/1 Applied online using this person's name." },
            new List<string> { "Barry Hewitt",	"(902) 735-5531",	"",	"1091",	"Barry.Hewitt@boeing.com",	"Jill Smith",	"Recpetionist",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jack Wick",	"(967) 198-0859",	"(967) 110-8360",	"1257",	"Jack.Wick@homedepot.com",	"Richard Cohen",	"Recpetionist",	"3/1 Applied online using this person's name." },
            new List<string> { "Theresa Olver",	"(202) 029-0761",	"",	"1932",	"Theresa.Olver@target.com",	"Irene Olver",	"Hoovers' Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Jill Hewitt",	"(902) 968-8765",	"(902) 638-8780",	"9299",	"Jill.Hewitt@wellpoint.com",	"Matt Voss",	"Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Peter Rudolph",	"(671) 930-3247",	"(671) 672-3891",	"6831",	"Peter.Rudolph@walgreen.com",	"Rick Johnson",	"Colleague",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Richard Olver",	"(902) 062-8821",	"(902) 705-0700",	"3729",	"Richard.Olver@jj.com",	"Rick Wick",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Theresa Stark",	"(671) 972-1385",	"(671) 944-3869",	"8298",	"Theresa.Stark@statefarm.com",	"Irene Cohen",	"Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Debbie Coopers",	"(212) 086-6610",	"(212) 967-4041",	"2056",	"Debbie.Coopers@medco.com",	"Barry Hewitt",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jackie Cohen",	"(212) 270-2878",	"(212) 787-1965",	"8518",	"Jackie.Cohen@microsoft.com",	"Josh Stark",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Matt Cohen",	"(671) 449-6131",	"",	"4393",	"Matt.Cohen@ut.com",	"Al McAveeney",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Barry Stark",	"(671) 319-7533",	"(671) 927-3751",	"8896",	"Barry.Stark@dell.com",	" ",	"Linked-In",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Theresa McAveeney",	"(212) 469-4741",	"(212) 162-9046",	"2766",	"Theresa.McAveeney@goldmansachs.com",	"David Cohen",	"Website",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Irene Spears",	"(967) 082-8203",	"",	"3553",	"Irene.Spears@pfizer.com",	" ",	"Linked-In",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Barry Jacobs",	"(202) 170-7183",	"(202) 740-3837",	"6635",	"Barry.Jacobs@marathon.com",	"Michael  Voss",	"Recpetionist",	"3/1 Applied online using this person's name." },
            new List<string> { "Irene Voss",	"(967) 713-8449",	"(967) 861-5925",	"4255",	"Irene.Voss@lowes.com",	" ",	"Recpetionist",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Richard Jacobs",	"(602) 827-6047",	"(602) 391-1773",	"3980",	"Richard.Jacobs@ups.com",	" ",	"Linked-In",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Irene Stein",	"(902) 050-4919",	"",	"7352",	"Irene.Stein@lockheed.com",	" ",	"Linked-In",	"3/1 Applied online using this person's name." },
            new List<string> { "Irene Voss",	"(212) 181-1205",	"(212) 512-3426",	"9163",	"Irene.Voss@bestbuy.com",	"Rick Hewitt",	"Hoovers' Website",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Irene Thornton",	"(902) 711-6220",	"",	"8896",	"Irene.Thornton@dow.com",	"Jim Rudolph",	"Recpetionist",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jackie Rudolph",	"(902) 904-9940",	"(902) 770-5418",	"3447",	"Jackie.Rudolph@supervalu.com",	"Theresa Perry",	"Hoovers' Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Michael  Stein",	"(902) 187-0461",	"(902) 828-2644",	"6585",	"Michael..Stein@sears.com",	" ",	"Linked-In",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Peter Stein",	"(602) 125-0140",	"",	"6976",	"Peter.Stein@iah.com",	"Richard Shapiro",	"Former Classmate",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Rhonda Shapiro",	"(967) 426-0439",	"(967) 910-6549",	"2956",	"Rhonda.Shapiro@pepsi.com",	"Jeff Olver",	"Colleague",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "David Jacobs",	"(902) 028-1897",	"(902) 543-9635",	"4109",	"David.Jacobs@metlife.com",	"Jill Shapiro",	"Former Classmate",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Barry Voss",	"(671) 331-2332",	"(671) 756-9948",	"8746",	"Barry.Voss@safeway.com",	"Theresa Wick",	"Linked-In",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Debbie Stark",	"(967) 208-6659",	"(967) 752-4703",	"8591",	"Debbie.Stark@kraft.com",	"Al Cruise",	"Former Classmate",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Al Jacobs",	"(212) 777-1846",	"",	"1637",	"Al.Jacobs@freddiemac.com",	"Jeff Jacobs",	"Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jackie Jacobs",	"(902) 493-8421",	"",	"9105",	"Jackie.Jacobs@sysco.com",	" ",	"Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jim Jacobs",	"(671) 501-6959",	"(671) 726-4743",	"9314",	"Jim.Jacobs@apple.com",	"Padma Cohen",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jack Thornton",	"(602) 768-8349",	"(602) 623-8787",	"6796",	"Jack.Thornton@disney.com",	"Richard Nelson",	"Hoovers' Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Josh Voss",	"(671) 177-3603",	"",	"1115",	"Josh.Voss@cisco.com",	"Jackie Rudolph",	"Former Classmate",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Jeff Voss",	"(202) 885-9642",	"(202) 481-9934",	"6994",	"Jeff.Voss@comcast.com",	"Debbie Olver",	"Hoovers' Website",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Peter Cruise",	"(671) 018-2158",	"(671) 899-2480",	"6395",	"Peter.Cruise@fedex.com",	"Jack Cohen",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Theresa Coopers",	"(671) 039-4234",	"",	"4013",	"Theresa.Coopers@northrop.com",	"Theresa Voss",	"Linked-In",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Barry Perry",	"(202) 017-3030",	"(202) 769-1859",	"4166",	"Barry.Perry@intel.com",	"David Olver",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Josh McAveeney",	"(202) 199-9072",	"(202) 513-5721",	"4676",	"Josh.McAveeney@aetna.com",	"Rick Cruise",	"Colleague",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Michael  Olver",	"(902) 898-0522",	"(902) 866-6703",	"2235",	"Michael..Olver@newyorklife.com",	"Rhonda Hewitt",	"Linked-In",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Theresa Jacobs",	"(902) 164-3600",	"",	"2213",	"Theresa.Jacobs@prudential.com",	" ",	"Colleague",	"3/1 Applied online using this person's name." },
            new List<string> { "Padma Cruise",	"(671) 122-5906",	"(671) 142-5283",	"3165",	"Padma.Cruise@caterpillar.com",	"Richard Cohen",	"Recpetionist",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Michael  Olver",	"(671) 117-0148",	"",	"2349",	"Michael..Olver@sprint.com",	" ",	"Linked-In",	"3/1 Applied online using this person's name." },
            new List<string> { "Jim Coopers",	"(602) 616-0997",	"(602) 360-9145",	"5309",	"Jim.Coopers@allstate.com",	" ",	"Former Classmate",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Richard Nelson",	"(967) 183-2917",	"",	"1906",	"Richard.Nelson@generaldynamics.com",	" ",	"Hoovers' Website",	"3/1 Applied online using this person's name." },
            new List<string> { "Peter Perry",	"(602) 822-3281",	"(602) 649-2469",	"2806",	"Peter.Perry@morganstanley.com",	" ",	"Former Classmate",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jack Cohen",	"(602) 189-5851",	"",	"5800",	"Jack.Cohen@cocacola.com",	"Jill Smith",	"Recpetionist",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Matt Smith",	"(902) 502-2416",	"(902) 669-9595",	"8444",	"Matt.Smith@humana.com",	" ",	"Colleague",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Nate Hewitt",	"(967) 521-4965",	"(967) 728-8882",	"8594",	"Nate.Hewitt@honeywell.com",	"Jim Cruise",	"Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jeff Jacobs",	"(967) 189-0064",	"",	"1668",	"Jeff.Jacobs@abbot.com",	" ",	"Recpetionist",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Jack Nelson",	"(602) 254-4278",	"(602) 412-5057",	"5415",	"Jack.Nelson@newscorp.com",	" ",	"Colleague",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Debbie Rudolph",	"(202) 822-5932",	"",	"3632",	"Debbie.Rudolph@hca.com",	"Jackie Nelson",	"Linked-In",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Jack Wick",	"(602) 062-0235",	"(602) 678-5077",	"2263",	"Jack.Wick@sunoco.com",	"Jack Coopers",	"Recpetionist",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jack Stark",	"(671) 098-0660",	"(671) 208-9528",	"1122",	"Jack.Stark@hess.com",	" ",	"Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Al Hewitt",	"(967) 522-1359",	"(967) 935-9102",	"4032",	"Al.Hewitt@ingram.com",	" ",	"Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Rick Voss",	"(902) 853-9482",	"",	"6673",	"Rick.Voss@fanniemae.com",	"Matt Wick",	"Colleague",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Michael  David",	"(602) 828-0843",	"",	"3567",	"Michael..David@walmart.com",	" ",	"Colleague",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Peter Rick",	"(902) 686-4490",	"(902) 082-2463",	"2750",	"Peter.Rick@exxon.com",	" ",	"Colleague",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Michael  Peter",	"(967) 604-2710",	"",	"2203",	"Michael..Peter@cheveron.com",	"Michael  Cruise",	"Colleague",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jack Rhonda",	"(671) 859-5458",	"(671) 636-8472",	"4213",	"Jack.Rhonda@ge.com",	"David Johnson",	"Linked-In",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Jill Jackie",	"(202) 827-1365",	"(202) 802-5373",	"5342",	"Jill.Jackie@bofa.com",	"David Perry",	"Former Classmate",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Peter Rick",	"(671) 425-8161",	"(671) 408-0424",	"8634",	"Peter.Rick@conoco.com",	"Padma Spears",	"Former Classmate",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Jackie Debbie",	"(202) 728-6779",	"",	"5734",	"Jackie.Debbie@att.com",	"Sandra Conner",	"Hoovers' Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Barry Jeff",	"(902) 296-7907",	"",	"3751",	"Barry.Jeff@ford.com",	"Irene McAveeney",	"Website",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Rick Debbie",	"(902) 938-3253",	"",	"9868",	"Rick.Debbie@jpmorgan.com",	" ",	"Former Classmate",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Michael  Theresa",	"(212) 497-7611",	"(212) 683-1547",	"3282",	"Michael..Theresa@hp.com",	"Jack Cohen",	"Website",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Irene Al",	"(202) 448-5600",	"(202) 272-9047",	"3321",	"Irene.Al@berkshire.com",	" ",	"Hoovers' Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Michael  Rhonda",	"(202) 491-5791",	"(202) 362-8126",	"3990",	"Michael..Rhonda@citi.com",	"Rick McAveeney",	"Former Classmate",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Michael  Nate",	"(671) 789-5971",	"",	"5838",	"Michael..Nate@verizon.com",	" ",	"Website",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Barry Jim",	"(202) 307-0813",	"",	"7374",	"Barry.Jim@mckesson.com",	" ",	"Hoovers' Website",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Josh Matt",	"(902) 247-0783",	"",	"2165",	"Josh.Matt@gm.com",	" ",	"Colleague",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Louise Jim",	"(212) 695-1357",	"6127885965",	"7543",	"Louise.Jim@aig.com",	"Rick Hewitt",	"Website",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Rhonda Al",	"(967) 115-8390",	"",	"3111",	"Rhonda.Al@cardinal.com",	"Josh Coopers",	"Linked-In",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Irene Louise",	"(212) 376-2757",	"(212) 591-5694",	"4478",	"Irene.Louise@cvs.com",	"Peter Perry",	"Colleague",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Barry Debbie",	"(212) 765-4486",	"(212) 574-6835",	"5817",	"Barry.Debbie@wellsfargo.com",	" ",	"Recpetionist",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Debbie Josh",	"(202) 847-6996",	"(202) 715-0238",	"3986",	"Debbie.Josh@ibm.com",	"Louise Stein",	"Website",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Josh Jackie",	"(902) 254-8293",	"",	"4046",	"Josh.Jackie@uhg.com",	"Jackie Voss",	"Recpetionist",	"3/1 Applied online using this person's name." },
            new List<string> { "Jill Peter",	"(967) 203-9279",	"(967) 403-2407",	"2249",	"Jill.Peter@pg.com",	"Al Jacobs",	"Linked-In",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Michael  Louise",	"(202) 843-2619",	"(202) 004-9348",	"4535",	"Michael..Louise@kroger.com",	"Jackie Johnson",	"Recpetionist",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Jim Padma",	"(602) 365-8824",	"(602) 822-5168",	"8769",	"Jim.Padma@amerisource.com",	" ",	"Hoovers' Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Peter Rick",	"(902) 600-9712",	"",	"3389",	"Peter.Rick@costco.com",	" ",	"Hoovers' Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Nate Josh",	"(212) 440-3245",	"(212) 131-8328",	"5490",	"Nate.Josh@valero.com",	"Rhonda Rudolph",	"Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Rhonda Rhonda",	"(967) 431-9797",	"",	"9469",	"Rhonda.Rhonda@adm.com",	"Barry Johnson",	"Hoovers' Website",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Jill Debbie",	"(902) 042-1332",	"(902) 204-7715",	"2012",	"Jill.Debbie@boeing.com",	"Jill Coopers",	"Colleague",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "David Jackie",	"(967) 861-4323",	"(967) 999-7727",	"8157",	"David.Jackie@homedepot.com",	"Jim Shapiro",	"Recpetionist",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Michael  Jill",	"(202) 116-9098",	"(202) 823-8630",	"4525",	"Michael..Jill@target.com",	"Jeff Olver",	"Former Classmate",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Padma Jackie",	"(902) 418-2388",	"",	"9802",	"Padma.Jackie@wellpoint.com",	"Barry Spears",	"Website",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Theresa Jack",	"(671) 462-0869",	"(671) 487-7049",	"9726",	"Theresa.Jack@walgreen.com",	"Peter Nelson",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jill Debbie",	"(902) 838-0836",	"(902) 851-4805",	"4076",	"Jill.Debbie@jj.com",	" ",	"Colleague",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jim Jill",	"(671) 336-9751",	"(671) 344-5754",	"1949",	"Jim.Jill@statefarm.com",	"Louise Wick",	"Former Classmate",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Michael  Nate",	"(212) 610-1089",	"",	"2221",	"Michael..Nate@medco.com",	"Peter Cruise",	"Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jeff Matt",	"(212) 509-8552",	"(212) 654-0492",	"3669",	"Jeff.Matt@microsoft.com",	" ",	"Recpetionist",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Jackie Al",	"(671) 690-3426",	"(671) 677-9890",	"4004",	"Jackie.Al@ut.com",	" ",	"Recpetionist",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jeff Al",	"(671) 405-6016",	"",	"7851",	"Jeff.Al@dell.com",	" ",	"Colleague",	"3/1 Applied online using this person's name." },
            new List<string> { "Jackie Jill",	"(212) 333-0856",	"",	"5017",	"Jackie.Jill@goldmansachs.com",	" ",	"Hoovers' Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Josh Jill",	"(967) 219-9982",	"(967) 126-9355",	"4373",	"Josh.Jill@pfizer.com",	"Al Stein",	"Hoovers' Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Matt Peter",	"(202) 076-9316",	"",	"5132",	"Matt.Peter@marathon.com",	" ",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Peter Jill",	"(967) 809-3107",	"",	"5544",	"Peter.Jill@lowes.com",	"Nate Wick",	"Linked-In",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Josh Jeff",	"(602) 632-8006",	"(602) 200-8379",	"9837",	"Josh.Jeff@ups.com",	"Jim Johnson",	"Hoovers' Website",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Debbie Jill",	"(902) 733-4897",	"(902) 462-5060",	"6985",	"Debbie.Jill@lockheed.com",	" ",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jill David",	"(212) 697-3225",	"",	"7252",	"Jill.David@bestbuy.com",	" ",	"Former Classmate",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Jeff Nate",	"(902) 369-3662",	"",	"8994",	"Jeff.Nate@dow.com",	"Debbie Spears",	"Recpetionist",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Debbie Jeff",	"(902) 471-5123",	"(902) 206-7437",	"9885",	"Debbie.Jeff@supervalu.com",	"Richard Hewitt",	"Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Josh Padma",	"(902) 518-3735",	"",	"3937",	"Josh.Padma@sears.com",	" ",	"Recpetionist",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Nate Jack",	"(602) 817-1674",	"",	"5751",	"Nate.Jack@iah.com",	"Louise Shapiro",	"Hoovers' Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jeff Jackie",	"(967) 452-1315",	"(967) 265-8683",	"9376",	"Jeff.Jackie@pepsi.com",	" ",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Barry Jack",	"(902) 356-8926",	"(902) 455-0148",	"3481",	"Barry.Jack@metlife.com",	" ",	"Linked-In",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Jill Al",	"(671) 791-0139",	"(671) 507-8278",	"5597",	"Jill.Al@safeway.com",	" ",	"Linked-In",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Peter Padma",	"(967) 537-1111",	"(967) 551-2285",	"3344",	"Peter.Padma@kraft.com",	"Jeff Smith",	"Former Classmate",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Peter Jeff",	"(212) 171-4769",	"(212) 124-2602",	"7518",	"Peter.Jeff@freddiemac.com",	"Rhonda Cruise",	"Colleague",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Al Rick",	"(902) 779-2634",	"(902) 408-0457",	"3490",	"Al.Rick@sysco.com",	"Michael  Olver",	"Hoovers' Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Richard Rick",	"(671) 946-7760",	"(671) 836-7903",	"9315",	"Richard.Rick@apple.com",	" ",	"Hoovers' Website",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Padma Rhonda",	"(602) 273-9288",	"",	"6002",	"Padma.Rhonda@disney.com",	"Richard Shapiro",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Padma Theresa",	"(671) 077-1531",	"(671) 076-0371",	"4771",	"Padma.Theresa@cisco.com",	" ",	"Linked-In",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Michael  Louise",	"(202) 733-0109",	"",	"2474",	"Michael..Louise@comcast.com",	" ",	"Linked-In",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Jack Louise",	"(671) 454-6293",	"(671) 589-9725",	"7660",	"Jack.Louise@fedex.com",	" ",	"Former Classmate",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "Rhonda Rick",	"(671) 870-9053",	"",	"1350",	"Rhonda.Rick@northrop.com",	"Matt Hewitt",	"Colleague",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Jeff Jill",	"(202) 739-9132",	"",	"2705",	"Jeff.Jill@intel.com",	"Jack Cruise",	"Linked-In",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Rick Jeff",	"(202) 250-0971",	"(202) 752-8025",	"2011",	"Rick.Jeff@aetna.com",	"Richard Smith",	"Colleague",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Jackie Peter",	"(902) 671-3179",	"",	"5805",	"Jackie.Peter@newyorklife.com",	"Louise Shapiro",	"Recpetionist",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Jim Josh",	"(902) 947-5870",	"",	"7040",	"Jim.Josh@prudential.com",	" ",	"Recpetionist",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Nate Barry",	"(671) 299-1817",	"",	"3404",	"Nate.Barry@caterpillar.com",	"Barry Stein",	"Former Classmate",	"3/1 Applied online using this person's name." },
            new List<string> { "Barry Josh",	"(671) 280-1643",	"(671) 008-4338",	"9390",	"Barry.Josh@sprint.com",	" ",	"Former Classmate",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Rhonda Rhonda",	"(602) 803-2719",	"",	"9458",	"Rhonda.Rhonda@allstate.com",	"Jeff Coopers",	"Former Classmate",	"5/1 They hired someone for the posted position. Call Chevy Chase to find if more positions available. " },
            new List<string> { "David Richard",	"(967) 223-7574",	"(967) 208-7653",	"8777",	"David.Richard@generaldynamics.com",	"Jackie Nelson",	"Website",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Debbie Jeff",	"(602) 725-3027",	"",	"5912",	"Debbie.Jeff@morganstanley.com",	"Jim Spears",	"Hoovers' Website",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Louise Debbie",	"(602) 722-8004",	"",	"6653",	"Louise.Debbie@cocacola.com",	"Jim Smith",	"Hoovers' Website",	"10/19 Says they may have a position available. Send resume and she will forward.   " },
            new List<string> { "Nate Barry",	"(902) 645-7605",	"(902) 235-2394",	"3508",	"Nate.Barry@humana.com",	" ",	"Recpetionist",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Jack Jeff",	"(967) 879-4139",	"(967) 539-7291",	"5977",	"Jack.Jeff@honeywell.com",	"Padma Jacobs",	"Colleague",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Jack Jill",	"(967) 378-4204",	"",	"8359",	"Jack.Jill@abbot.com",	" ",	"Recpetionist",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Rhonda Nate",	"(602) 058-4378",	"(602) 263-0695",	"4095",	"Rhonda.Nate@newscorp.com",	" ",	"Hoovers' Website",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "Michael  Debbie",	"(202) 054-4533",	"(202) 908-6671",	"8872",	"Michael..Debbie@hca.com",	"Barry Coopers",	"Former Classmate",	"2/29  Thanked me for calling. No position available but call back in 3 months." },
            new List<string> { "Jackie Jack",	"(602) 637-7762",	"(602) 318-6333",	"4144",	"Jackie.Jack@sunoco.com",	"Josh Cruise",	"Recpetionist",	"1/19 Says this was an interesting time to call - they are borrowing resources and need help. Send resume and follow-up Thurs / Fri." },
            new List<string> { "Jack Jack",	"(671) 582-1022",	"(671) 838-5209",	"4050",	"Jack.Jack@hess.com",	" ",	"Colleague",	"11/17 Returned my call. I need to talk with product development - they do segmentation, prod launch, etc. " },
            new List<string> { "Jack Josh",	"(967) 977-7049",	"(967) 601-3516",	"3186",	"Jack.Josh@ingram.com",	"Jill Perry",	"Hoovers' Website",	"3/1 Applied online using this person's name." },
            new List<string> { "Louise Jim",	"(902) 524-8475",	"",	"8109",	"Louise.Jim@fanniemae.com",	"Jim Coopers",	"Linked-In",	"4/16 No answer.  Left a voicemail." },
            new List<string> { "No Name",	"",	"",	"",	"",	"",	"",	"" },
            new List<string> { "Allison Jones",	"602-992-0924",	"",	"",	"ajones@att.com",	"",	"Alumni Database",	"" },
            new List<string> { "Josh Samsom",	"",	"",	"",	"",	"",	"",	"" },
            new List<string> { "Allison Jones",	"6028282994",	"",	"",	"ajones@att.com",	"",	"Alumni Database",	"" },
            new List<string> { "Allison Jones",	"",	"878-998-3276",	"",	"jones@aol.com",	"",	"Alumni Database",	"" },
            new List<string> { "Avinash Padhye",	"",	"",	"",	"",	"",	"",	"", }
        };
        #endregion

        public List<string> TaskNames = new List<string>
        {
            { "Adding a Task" },
            { "Apply online" },
            { "Call and Introduce" },
            { "Call back tomorrow" },
            { "Call for Introduction" },
            { "Call" },
            { "Follow-up with a phone call" },
            { "Message him" },
            { "Send email" },
            { "Send in Application" },
            { "Send them Resume" },
            { "Test Task" },
            { "Update" },
        };
    }
}