#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.ContactSearch.Views.Jigsaw
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/ContactSearch/Views/Jigsaw/_SearchForm.cshtml")]
    public class _SearchForm : System.Web.Mvc.WebViewPage<MyJobLeads.Areas.ContactSearch.Models.JigsawSearchParametersViewModel>
    {
        public _SearchForm()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"pageInfoBox\">\r\n");


            
            #line 5 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
         using (Html.BeginForm(MVC.ContactSearch.Jigsaw.PerformSearch(), FormMethod.Get))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 marginAuto floatLeft\"> \r\n          " +
"      <h3 class=\"floatLeft\">Jigsaw Contact Search</h3> \r\n            </div> \r\n");


            
            #line 10 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 marginAuto floatleft\">\r\n           " +
"     <div class=\"floatLeft infoSpan\">\r\n                    ");


            
            #line 13 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
               Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");


            
            #line 16 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">First Name:</p>\r\n                    " +
"<div class=\"infoSpan\">");


            
            #line 19 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                     Write(Html.TextBoxFor(x => x.FirstName, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n\r\n                <div class=\"floatLeft\"><p clas" +
"s=\"greyHighlight\">Last Name:</p>\r\n                    <div class=\"infoSpan\">");


            
            #line 23 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                     Write(Html.TextBoxFor(x => x.LastName, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>                   \r\n            </div> \r\n");


            
            #line 26 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Title:</p>\r\n                    <div " +
"class=\"infoSpan\">");


            
            #line 29 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                     Write(Html.TextBoxFor(x => x.Title, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n\r\n                <div class=\"floatLeft\"><p clas" +
"s=\"greyHighlight\">Company Name:</p>\r\n                    <div class=\"infoSpan\">");


            
            #line 33 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                     Write(Html.TextBoxFor(x => x.Company, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>                   \r\n            </div> \r\n");


            
            #line 36 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
 

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Department:</p>\r\n                    " +
"<div class=\"infoSpan\">");


            
            #line 39 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                     Write(Html.DropDownListFor(x => x.Departments, Model.DepartmentList, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n\r\n                <div class=\"floatLeft\"><p clas" +
"s=\"greyHighlight\">Industry:</p>\r\n                    <div class=\"infoSpan\">");


            
            #line 43 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                     Write(Html.DropDownListFor(x => x.Industry, Model.IndustryList));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>                   \r\n            </div> \r\n");


            
            #line 46 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Level:</p>\r\n                    <div " +
"class=\"infoSpan\">");


            
            #line 49 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                                     Write(Html.DropDownListFor(x => x.Levels, Model.LevelsList, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>                    \r\n            </div>\r\n");


            
            #line 52 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_20 floatLeft\"> \r\n                <div " +
"class=\"submitBTN \">\r\n                    <input type=\"submit\" value=\"Search\" />\r" +
"\n                </div>\r\n            </div>\r\n");


            
            #line 58 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"clear\"></div>\r\n");


            
            #line 60 "..\..\Areas\ContactSearch\Views\Jigsaw\_SearchForm.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div> \r\n</div> ");


        }
    }
}
#pragma warning restore 1591
