#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/_LoggedInSidebarDisplay.cshtml")]
    public class _LoggedInSidebarDisplay : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Users.UserSidebarViewModel>
    {
        public _LoggedInSidebarDisplay()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<p>\r\n    <span id=\"user-name\">");


            
            #line 4 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Home\_LoggedInSidebarDisplay.cshtml"
                    Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral(@"</span> <br />
    <a href=""#"" id=""edit-account-link"">Edit My Account</a>
</p>
    			
<p id=""sidebar-links"">
    <a href=""#"">My Tasks</a><br />
    <a href=""#"">Contacts</a><br />
    <a href=""#"">Companies</a><br />
    <br />
    <a href=""#"">About</a><br />
    ");


            
            #line 14 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Home\_LoggedInSidebarDisplay.cshtml"
Write(Html.ActionLink("Log out", MVC.Account.LogOff()));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>");


        }
    }
}
#pragma warning restore 1591
