#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/About.cshtml")]
    public class About : System.Web.Mvc.WebViewPage<dynamic>
    {
        public About()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Home\About.cshtml"
  
    ViewBag.Title = "About Us";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideBar", () => {

WriteLiteral("\r\n");


            
            #line 6 "..\..\Views\Home\About.cshtml"
      Html.RenderAction(MVC.Home.SidebarDisplay(MyJobLeads.Controllers.ActiveSidebarLink.About));

            
            #line default
            #line hidden

});

WriteLiteral(@"

<div class=""grid1 floatLeft""> 
    <div class=""lineSeperater""> 
        <div class=""pageInfoBox""> 
            <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
                <h3>About MyLeads</h3>
            </div>

            <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
                <p>
                    MyLeads version 3.0. Property of <a class=""inlineBlue"" href=""http://interviewtools.net"">InterviewTools</a>.
                </p>

                <p>
                    Please contact us at <a class=""inlineBlue"" href=""mailto:support@interviewtools.net"">support@interviewtools.net</a>
                </p>
            </div>
            
            <div class=""clear""></div>
        </div>
    </div>
</div>");


        }
    }
}
#pragma warning restore 1591
