#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/JigsawError.cshtml")]
    public class JigsawError : System.Web.Mvc.WebViewPage<dynamic>
    {
        public JigsawError()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Home\JigsawError.cshtml"
  
    ViewBag.Title = "A Jigsaw Error Has Occurred";


            
            #line default
            #line hidden
WriteLiteral(@"
<div class=""grid1 floatLeft""> 
    <div class=""pageInfoBox""> 
        <div class=""grid3 marginBottom_10 marginAuto floatLeft""> 
            <h3 class=""floatLeft"">A Jigsaw Error Has Occurred</h3> 
        </div> 
                
        <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
            <div class=""floatLeft"">
                <p>
                    An unexpected error has occurred while attempting to contact the Jigsaw database.  
                    The system administrators have been notified, and we apologize for the inconvenience.
                </p>    
            </div>
        </div>

        <div class=""clear""></div> 
    </div> 
</div>
");


        }
    }
}
#pragma warning restore 1591
