#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.CompanySearch.Views.Jigsaw
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CompanySearch/Views/Jigsaw/_SearchForm.cshtml")]
    public class _SearchForm : System.Web.Mvc.WebViewPage<MyJobLeads.Areas.CompanySearch.Models.Jigsaw.CompanySearchQueryViewModel>
    {
        public _SearchForm()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\CompanySearch\Views\Jigsaw\_SearchForm.cshtml"
 using (Html.PageInfoBox(false))
{
    using (Html.BeginForm(MVC.CompanySearch.Jigsaw.PerformSearch(), FormMethod.Get))
    {
        
            
            #line default
            #line hidden
            
            #line 7 "..\..\Areas\CompanySearch\Views\Jigsaw\_SearchForm.cshtml"
   Write(Html.HiddenFor(x => x.MergeCompanyId));

            
            #line default
            #line hidden
            
            #line 7 "..\..\Areas\CompanySearch\Views\Jigsaw\_SearchForm.cshtml"
                                              
        
        using (Html.OuterRow())
        {

            
            #line default
            #line hidden
WriteLiteral("            <h3>Jigsaw Company Search</h3>\r\n");


            
            #line 12 "..\..\Areas\CompanySearch\Views\Jigsaw\_SearchForm.cshtml"
        }

        using (Html.OuterRow())
        {
            using (Html.ValidationArea())
            {
                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\CompanySearch\Views\Jigsaw\_SearchForm.cshtml"
           Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\CompanySearch\Views\Jigsaw\_SearchForm.cshtml"
                                         
            }
        }

        using (Html.OuterRow())
        {
            Html.FormField("Company Name", Html.TextBoxFor(x => x.CompanyName, new { @class = "info" }));
            Html.FormField("Industry", Html.DropDownListFor(x => x.Industry, Model.IndustryList));
        }

        using (Html.OuterRow())
        {
            Html.FormField("Metro Area", Html.DropDownListFor(x => x.MetroArea, Model.MetroAreaList, new { @class = "info" }));
            Html.FormField("State", Html.DropDownListFor(x => x.State, Model.StateList, new { @class = "info" }));
        }

        using (Html.OuterRow())
        {
            Html.FormField("Ownership", Html.DropDownListFor(x => x.Ownership, Model.OwnershipTypes, new { @class = "info" }));
            Html.FormField("Number of Employees", Html.DropDownListFor(x => x.Employees, Model.EmployeeList, new { @class = "info" }));
        }

        using (Html.OuterRow())
        {
            using (Html.FormButtonArea())
            {

            
            #line default
            #line hidden
WriteLiteral("                <input type=\"submit\" value=\"Search\" />\r\n");


            
            #line 45 "..\..\Areas\CompanySearch\Views\Jigsaw\_SearchForm.cshtml"
            }
        }
    }
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
