#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.CompanySearch.Views.Jigsaw
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/CompanySearch/Views/Jigsaw/AddCompany.cshtml")]
    public class AddCompany : System.Web.Mvc.WebViewPage<MyJobLeads.Areas.CompanySearch.Models.Jigsaw.AddCompanyViewModel>
    {
        public AddCompany()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
  
    ViewBag.Title = "Add Jigsaw Company";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideBar", () => {

WriteLiteral("\r\n");


            
            #line 8 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
      Html.RenderAction(MVC.Home.SidebarDisplay(MyJobLeads.Controllers.ActiveSidebarLink.ResearchCenter));

            
            #line default
            #line hidden

});

WriteLiteral("\r\n\r\n");


            
            #line 11 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
 using (Html.PageInfoBox(false))
{
    using (Html.BeginForm())
    {
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
   Write(Html.HiddenFor(x => x.JigsawCompanyName));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
                                                 
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
   Write(Html.HiddenFor(x => x.JigsawId));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
                                        

        using (Html.OuterRow())
        {

            
            #line default
            #line hidden
WriteLiteral("            <h3>Add ");


            
            #line 20 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
               Write(Model.JigsawCompanyName);

            
            #line default
            #line hidden
WriteLiteral(" To MyLeads</h3>\r\n");


            
            #line 21 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
        }

        using (Html.OuterRow())
        {
            using (Html.ValidationArea())
            {
                
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
           Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
                                         
            }
        }

        using (Html.OuterRow())
        {
            using (Html.ContentArea())
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    ");


            
            #line 36 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
               Write(Html.LabelFor(x => x.CreateNewCompany, "Create new company in MyLeads for " + Model.JigsawCompanyName + ":"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");


            
            #line 37 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
               Write(Html.CheckBoxFor(x => x.CreateNewCompany));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </p>\r\n");


            
            #line 39 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
            }
        }

        using (Html.OuterRow())
        {
            using (Html.ContentArea())
            {

            
            #line default
            #line hidden
WriteLiteral("                <p><span class=\"bold\">OR</span></p>\r\n");


            
            #line 47 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
            }
        }

        using (Html.OuterRow())
        {
            using (Html.ContentArea())
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    Sync with existing company: ");


            
            #line 55 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
                                           Write(Html.DropDownListFor(x => x.ExistingCompanyId, Model.ExistingCompanyList));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </p>\r\n");


            
            #line 57 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
            }
        }

        using (Html.OuterRow())
        {
            using (Html.FormButtonArea())
            {

            
            #line default
            #line hidden
WriteLiteral("                <input type=\"submit\" value=\"Save\" />\r\n");


            
            #line 65 "..\..\Areas\CompanySearch\Views\Jigsaw\AddCompany.cshtml"
            }
        }
    }
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
