#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.FillPerfect.Views.OrgPilotDashboard
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/FillPerfect/Views/OrgPilotDashboard/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<MyJobLeads.Areas.FillPerfect.Models.Pilot.OrgDashboardViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
  
    ViewBag.Title = "FillPerfect Pilot Control Screen";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 7 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
 using (Html.PageInfoBox(false))
{
    using (Html.OuterRow())
    {

            
            #line default
            #line hidden
WriteLiteral("        <h3>Welcome To Your FillPerfect Control Screen</h3>\r\n");


            
            #line 12 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
    }

    using (Html.OuterRow())
    {
        using (Html.ContentArea())
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>Thanks for testing  InterviewTools FillPerfect.</p>\r\n");


            
            #line 19 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"            <p>
                We’ve allotted your school free copies of FillPerfect (3-Month Licenses), to distribute to students as you see fit. 
                In return for using this  unrestricted copy, students must agree to provide you feedback on their usage – 
                number of applications they’ve used this tool for,  how users have rated the system, and any written comments they wish to give. 
            </p>
");


            
            #line 25 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <p>To send a copy to your students, use the Test Pilot Control Screen" +
" below.</p>\r\n");


            
            #line 27 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <p>For any questions, contact us using the form at the bottom of this" +
" page.</p>\r\n");


            
            #line 29 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <p>Read our Career Services FillPerfect Welcome Package for more deta" +
"ils on this pilot program.</p>\r\n");


            
            #line 31 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
        }
    }

    using (Html.OuterRow())
    {
        using (Html.ContentArea())
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>\r\n                <span class=\"bold\">Total Licenses Alotted:</span" +
"> ");


            
            #line 39 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                                                             Write(Model.AlottedLicenseCount);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n                <span class=\"bold\">Free Licenses Remaining:</span> ");


            
            #line 40 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                                                              Write(Model.RemainingLicenseCount);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n            </p>\r\n");


            
            #line 42 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
    
            using (Html.BeginForm(MVC.FillPerfect.OrgPilotDashboard.SendPilotLicense()))
            {
                using (Html.ValidationArea())
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p>\r\n                        ");


            
            #line 48 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                   Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n");


            
            #line 50 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                }

                //using (Html.ContentArea())
                //{

            
            #line default
            #line hidden
WriteLiteral("                    <p>\r\n                        <br />\r\n                        " +
"<br />\r\n                        <span class=\"bold\">Send License to:</span><br />" +
"\r\n                        Student Name: ");


            
            #line 58 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                                 Write(Html.TextBox("name", "", new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral(" &nbsp;\r\n                        Student Email: ");


            
            #line 59 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                                  Write(Html.TextBox("email", "", new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 61 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                         using (Html.FormButtonArea())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <input type=\"submit\" value=\"Send\" />\r\n");


            
            #line 64 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </p>\r\n");


            
            #line 66 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                //}
            }
        }
    }

    using (Html.OuterRow())
    {

            
            #line default
            #line hidden
WriteLiteral("            <h3>Used Licenses</h3>\r\n");



WriteLiteral("            <table class=\"display\">\r\n                <thead>\r\n                   " +
" <th>Name</th>\r\n                    <th>Email</th>\r\n                    <th>Lice" +
"nse Sent On</th>\r\n                    <th></th>\r\n                </thead>\r\n\r\n");


            
            #line 82 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                 foreach (var user in Model.LicensedUsers)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>");


            
            #line 85 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                       Write(user.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td><a href=\"mailto:");


            
            #line 86 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                                       Write(user.Email);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"inlineBlue\">");


            
            #line 86 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                                                                       Write(user.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                        <td>");


            
            #line 87 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                       Write(user.GrantedDate.ToString("D"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>\r\n                            ");


            
            #line 89 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                       Write(Html.ActionLink("Resend License Information", MVC.FillPerfect.OrgPilotDashboard.ResendLicense(user.Id), new { @class = "inlineBlue" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>   \r\n");


            
            #line 92 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 94 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                 if (Model.LicensedUsers.Count == 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>You have not sent any licen" +
"ses out yet</td>\r\n                    </tr>   \r\n");


            
            #line 99 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n");


            
            #line 101 "..\..\Areas\FillPerfect\Views\OrgPilotDashboard\Index.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
