#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.PositionSearch.Views.LinkedIn
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PositionSearch/Views/LinkedIn/AddPosition.cshtml")]
    public class AddPosition : System.Web.Mvc.WebViewPage<MyJobLeads.Areas.PositionSearch.Models.AddPositionViewModel>
    {
        public AddPosition()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
  
    ViewBag.Title = "Add Position From LinkedIn";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"pageInfoBox\"> \r\n");


            
            #line 9 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
         using (Html.BeginForm()) 
        {
            
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
       Write(Html.HiddenFor(x => x.PositionId));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                                              
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
       Write(Html.HiddenFor(x => x.PositionTitle));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                                                 
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
       Write(Html.HiddenFor(x => x.CompanyName));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                                               
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 marginAuto floatLeft\"> \r\n          " +
"      <h3 class=\"floatLeft\">Add LinkedIn Position To Your Job Search</h3> \r\n    " +
"        </div> \r\n");


            
            #line 18 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 marginAuto floatLeft\">\r\n           " +
"     <div class=\"floatLeft\">\r\n                    <p>\r\n                        P" +
"osition: <span class=\"bold\">");


            
            #line 22 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                                                Write(Model.PositionTitle);

            
            #line default
            #line hidden
WriteLiteral("</span><br />\r\n                        Company: <span class=\"bold\">");


            
            #line 23 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                                               Write(Model.CompanyName);

            
            #line default
            #line hidden
WriteLiteral("</span><br />\r\n                        Source: <a href=\"http://www.linkedin.com/j" +
"obs?viewJob=&jobId=");


            
            #line 24 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                                                                                Write(Url.Encode(Model.PositionId));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"inlineBlue\">LinkedIn</a>\r\n                    </p>    \r\n                " +
"</div>\r\n            </div>\r\n");


            
            #line 28 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 marginAuto floatleft\">\r\n           " +
"     <div class=\"floatLeft infoSpan\">\r\n                    ");


            
            #line 31 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
               Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");


            
            #line 34 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\">\r\n                    <p class=\"greyHighlight\">");


            
            #line 37 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                                        Write(Html.LabelFor(x => x.CreateNewCompany, "Create Company Entry For " + Model.CompanyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 38 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                   Write(Html.CheckBoxFor(x => x.CreateNewCompany));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n                </div> \r\n            </div> \r\n");


            
            #line 42 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""grid3 marginBottom_10 floatLeft""> 
                <div class=""floatLeft"">
                    <p class=""greyHighlight""><span class=""bold"">OR</span></p>
                    <p class=""greyHighlight"">Add Position To Existing Company:</p>
                    <div class=""infoSpan"">
                        ");


            
            #line 48 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
                   Write(Html.DropDownListFor(x => x.SelectedCompany, Model.CompanyList));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div> \r\n            </div> \r\n");


            
            #line 52 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_20 floatLeft\"> \r\n                <div " +
"class=\"submitBTN \">\r\n                    <input type=\"submit\" value=\"Add Positio" +
"n\" /> &nbsp;\r\n                    ");


            
            #line 56 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
               Write(Html.ActionLink("Cancel", MVC.PositionSearch.LinkedIn.PositionDetails(Model.PositionId)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>                    \r\n            </div> \r\n");


            
            #line 59 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPosition.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div> \r\n    </div> \r\n</div> \r\n");


        }
    }
}
#pragma warning restore 1591
