#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.PositionSearch.Views.LinkedIn
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PositionSearch/Views/LinkedIn/AddPositionSuccessful.cshtml")]
    public class AddPositionSuccessful : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.ViewModels.PositionSearching.ExternalPositionAddedResultViewModel>
    {
        public AddPositionSuccessful()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPositionSuccessful.cshtml"
  
    ViewBag.Title = "Position Successfully Added";


            
            #line default
            #line hidden
WriteLiteral(@"
<div class=""grid1 floatLeft""> 
    <div class=""pageInfoBox""> 
        <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
            <h3>Position Added To Your Job Search</h3>
        </div>

        <div class=""grid3 marginBottom_10 marginAuto floatLeft"">
            <p>
                You have successfully added
                ");


            
            #line 16 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPositionSuccessful.cshtml"
           Write(Html.ActionLink(Model.PositionTitle, MVC.Position.Details(Model.PositionId), new { @class = "inlineBlue", title = "View Position Details" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                to your job search for the\r\n                ");


            
            #line 18 "..\..\Areas\PositionSearch\Views\LinkedIn\AddPositionSuccessful.cshtml"
           Write(Html.ActionLink(Model.CompanyName, MVC.Company.Details(Model.CompanyId), new { @class = "inlineBlue", title = "View Company Details" }));

            
            #line default
            #line hidden
WriteLiteral(".\r\n            </p>\r\n        </div>\r\n            \r\n        <div class=\"clear\"></d" +
"iv>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
