#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.PositionSearch.Views.LinkedIn
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PositionSearch/Views/LinkedIn/PerformSearch.cshtml")]
    public class PerformSearch : System.Web.Mvc.WebViewPage<MyJobLeads.Areas.PositionSearch.Models.PerformedSearchViewModel>
    {
        public PerformSearch()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
  
    ViewBag.Title = "LinkedIn Job Search";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideBar", () => {

WriteLiteral("\r\n");


            
            #line 8 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
      Html.RenderAction(MVC.Home.SidebarDisplay(MyJobLeads.Controllers.ActiveSidebarLink.PositionSearch));

            
            #line default
            #line hidden

});

WriteLiteral("\r\n\r\n");


            
            #line 11 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
  Html.RenderPartial(MVC.PositionSearch.LinkedIn.Views._SearchForm, Model.SearchQuery);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 13 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
 if (Model.Results != null)
{
    string urlParams = string.Format("Keywords={0}&SelectedCountry={1}&PostalCode={2}",
                                        Url.Encode(Model.SearchQuery.Keywords),
                                        Url.Encode(Model.SearchQuery.SelectedCountryCode),
                                        Url.Encode(Model.SearchQuery.PostalCode));

    int firstResultCount = Model.Results.PageNum * Model.Results.PageSize + 1;
    int lastResultCount = firstResultCount + Model.Results.Results.Count - 1;
    
    int totalPages = Model.Results.TotalCount / Model.Results.PageSize;
    if (Model.Results.TotalCount % Model.Results.PageSize != 0) { totalPages++; }
    

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"grid3 floatLeft\">\r\n        <div class=\"positionResultsHeader\">\r\n");


            
            #line 28 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
             if (Model.Results.TotalCount == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <h3>No Positions Found Matching Your Criteria</h3>\r\n");


            
            #line 31 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <h3>Found Positions (displaying ");


            
            #line 34 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                           Write(firstResultCount);

            
            #line default
            #line hidden
WriteLiteral(" - ");


            
            #line 34 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                               Write(lastResultCount);

            
            #line default
            #line hidden
WriteLiteral(" out of ");


            
            #line 34 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                       Write(Model.Results.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(")</h3>\r\n");


            
            #line 35 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            <ul class=\"positionSearchNotification\">\r\n                <li>Page ");


            
            #line 38 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                     Write(Model.Results.TotalCount > 0 ? Model.Results.PageNum + 1 : 0);

            
            #line default
            #line hidden
WriteLiteral(" of ");


            
            #line 38 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                       Write(totalPages);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\r\n");


            
            #line 40 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                 if (Model.Results.PageNum > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a href=\"");


            
            #line 43 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                            Write(Url.Action(MVC.PositionSearch.LinkedIn.PerformSearch()));

            
            #line default
            #line hidden
WriteLiteral("?");


            
            #line 43 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                     Write(urlParams);

            
            #line default
            #line hidden
WriteLiteral("&pageNum=");


            
            #line 43 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                                         Write(Model.Results.PageNum - 1);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Previous Page\r\n                        </a>\r\n    " +
"                </li>\r\n");


            
            #line 47 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                \r\n");


            
            #line 49 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                 if (Model.Results.PageNum < totalPages - 1)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a href=\"");


            
            #line 52 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                            Write(Url.Action(MVC.PositionSearch.LinkedIn.PerformSearch()));

            
            #line default
            #line hidden
WriteLiteral("?");


            
            #line 52 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                     Write(urlParams);

            
            #line default
            #line hidden
WriteLiteral("&pageNum=");


            
            #line 52 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                                         Write(Model.Results.PageNum + 1);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Next Page\r\n                        </a>\r\n        " +
"            </li>               \r\n");


            
            #line 56 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>       \r\n        </div>\r\n\r\n        <div id=\"positionRole\">\r\n    " +
"        <ul>\r\n");


            
            #line 62 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                 foreach (var position in Model.Results.Results)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a href=\"");


            
            #line 65 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                            Write(Url.Action(MVC.PositionSearch.LinkedIn.PositionDetails(position.JobId)));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"View Position Details\">\r\n                            <div class=\"taskNam" +
"e\">");


            
            #line 66 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                             Write(position.Company);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"positionSubHeading\">");


            
            #line 67 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                       Write(position.Location);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"taskDescription\">");


            
            #line 68 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                    Write(position.Description);

            
            #line default
            #line hidden
WriteLiteral("...</div>\r\n                        </a>\r\n                    </li>\r\n");


            
            #line 71 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n\r\n        <div class=\"lowerPositionResultsHead" +
"er\">\r\n");


            
            #line 76 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
             if (Model.Results.TotalCount == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <h3>No Positions Found Matching Your Criteria</h3>\r\n");


            
            #line 79 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <h3>Found Positions (displaying ");


            
            #line 82 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                           Write(firstResultCount);

            
            #line default
            #line hidden
WriteLiteral(" - ");


            
            #line 82 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                               Write(lastResultCount);

            
            #line default
            #line hidden
WriteLiteral(" out of ");


            
            #line 82 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                       Write(Model.Results.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(")</h3>\r\n");


            
            #line 83 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            <ul class=\"positionSearchNotification\">\r\n                <li>Page ");


            
            #line 86 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                     Write(Model.Results.TotalCount > 0 ? Model.Results.PageNum + 1 : 0);

            
            #line default
            #line hidden
WriteLiteral(" of ");


            
            #line 86 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                       Write(totalPages);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\r\n");


            
            #line 88 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                 if (Model.Results.PageNum > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a href=\"");


            
            #line 91 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                            Write(Url.Action(MVC.PositionSearch.LinkedIn.PerformSearch()));

            
            #line default
            #line hidden
WriteLiteral("?");


            
            #line 91 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                     Write(urlParams);

            
            #line default
            #line hidden
WriteLiteral("&pageNum=");


            
            #line 91 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                                         Write(Model.Results.PageNum - 1);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Previous Page\r\n                        </a>\r\n    " +
"                </li>\r\n");


            
            #line 95 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                \r\n");


            
            #line 97 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                 if (Model.Results.PageNum < totalPages - 1)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a href=\"");


            
            #line 100 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                            Write(Url.Action(MVC.PositionSearch.LinkedIn.PerformSearch()));

            
            #line default
            #line hidden
WriteLiteral("?");


            
            #line 100 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                     Write(urlParams);

            
            #line default
            #line hidden
WriteLiteral("&pageNum=");


            
            #line 100 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                                                                                                         Write(Model.Results.PageNum + 1);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            Next Page\r\n                        </a>\r\n        " +
"            </li>               \r\n");


            
            #line 104 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>       \r\n        </div>\r\n    </div>\r\n");


            
            #line 108 "..\..\Areas\PositionSearch\Views\LinkedIn\PerformSearch.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
