#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.JobSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/JobSearch/_JsMilestoneDisplay.cshtml")]
    public class _JsMilestoneDisplay : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Tasks.TaskDashboardViewModel>
    {
        public _JsMilestoneDisplay()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
 if (Model.CurrentMilestone != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"milestone-display\">\r\n        <b>Current Milestone:</b> <br />\r\n     " +
"   <span class=\"item-heading\">");


            
            #line 7 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
                              Write(Model.CurrentMilestone.Title);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\r\n        <span class=\"item-subheading\">Percent Completed: ");


            
            #line 8 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
                                                    Write(Math.Round(Model.MilestoneProgress.TotalProgress * 100, 1));

            
            #line default
            #line hidden
WriteLiteral("%</span> <br /> <br />\r\n\r\n");


            
            #line 10 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
         if (Model.MilestoneProgress.TotalProgress == 1)
        {
            
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
       Write(Html.Raw(Html.Encode(Model.CurrentMilestone.CompletionDisplay).Replace(Environment.NewLine, "<br />")));

            
            #line default
            #line hidden

WriteLiteral(" <br />");



WriteLiteral("<br />\r\n");


            
            #line 13 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <span class=\"rights\"><a href=\"#\">Start Next Milestone</a></span>\r\n");


            
            #line 15 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
        }
        
        else
        {
            
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
       Write(Html.Raw(Html.Encode(Model.CurrentMilestone.Instructions).Replace(Environment.NewLine, "<br />")));

            
            #line default
            #line hidden
            
            #line 19 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
                                                                                                              
        }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 22 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\_JsMilestoneDisplay.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
