#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.JobSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
    using MyJobLeads.DomainModel.Entities;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
    using MyJobLeads.Infrastructure.HtmlHelpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/JobSearch/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.JobSearches.JobSearchDetailsViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


            
            #line 5 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
  
    ViewBag.Title = Model.JobSearch.Name + " - Job Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Sidebar = Html.Partial(MVC.Task.Views._OpenTaskSummary, Model.OpenTasks);


            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>");


            
            #line 11 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
Write(Model.JobSearch.Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n<br />\r\n\r\n<p>\r\n    ");


            
            #line 15 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
Write(Html.ActionLink("Edit This Job Search", MVC.JobSearch.Edit(Model.JobSearch.Id)));

            
            #line default
            #line hidden
WriteLiteral(" &nbsp; \r\n    ");


            
            #line 16 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
Write(Html.ActionLink("View All Job Searches", MVC.JobSearch.Index()));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n\r\n<p>\r\n");


            
            #line 20 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.JobSearch.Description)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("<b>Description:</b> ");


            
            #line 20 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
                                                                                         Write(Model.JobSearch.Description);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 20 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
                                                                                                                                  }

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n<p>\r\n");


            
            #line 24 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
     using (Html.BeginForm(MVC.JobSearch.Search(), FormMethod.Get))
    {
        
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
   Write(Html.Hidden("id", Model.JobSearch.Id));

            
            #line default
            #line hidden
            
            #line 26 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
                                              

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("Search: ");


            
            #line 27 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
             Write(Html.TextBox("query"));

            
            #line default
            #line hidden
WriteLiteral(" <input type=\"submit\" value=\"Search\" />\r\n");


            
            #line 28 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n<h2>Job Search Progress</h2>\r\n<hr />\r\n\r\n");


            
            #line 34 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
   Html.RenderPartial(MVC.JobSearch.Views._JsMilestoneDisplay, Model.JobSearch);   

            
            #line default
            #line hidden
WriteLiteral("\r\n <br /><br />\r\n <h2>Companies</h2>\r\n <hr />\r\n\r\n <p>\r\n    ");


            
            #line 41 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
Write(Html.ActionLink("Add A New Company", MVC.Company.Add(@Model.JobSearch.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                \r\n    <ul>\r\n");


            
            #line 44 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
         foreach (Company company in @Model.JobSearch.Companies.OrderBy(x => x.Name).ToList())
        {

            
            #line default
            #line hidden
WriteLiteral("            <li>");


            
            #line 46 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
           Write(Html.ActionLink(company.Name, MVC.Company.Details(company.Id)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");


            
            #line 47 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n</p>");


        }
    }
}
#pragma warning restore 1591
