#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.JobSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/JobSearch/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.Entities.JobSearch>
    {
        public Edit()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";
    bool isNewJobSearch = Model.Id == 0;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 8 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
 if (isNewJobSearch)
{
    ViewBag.Title = "Start a New Job Search";
    

            
            #line default
            #line hidden
WriteLiteral("    <h2>Start a New Job Search</h2>\r\n");



WriteLiteral(@"    <p>
        Your first step is to setup a job search. Interview Tools allows you to organize multiple job searches. Some uses of this are:
        <ul>
            <li>Organize your job search by year, such as ""2011 Full Time Position"", ""2012 Internship Hunt"", or ""May 2012 Need Part-Time Job""</li>
            <li>Organize job search by function, such as ""Sales and Marketing Opportunities"" or ""Engineering Job Search""</li>
        </ul>
    </p>
");


            
            #line 20 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
}
else
{
    ViewBag.Title = "Editing " + @Model.Name;
    

            
            #line default
            #line hidden
WriteLiteral("    <h2>Editing the \'");


            
            #line 25 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
                Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\' Job Search</h2>\r\n");



WriteLiteral("    <div class=\"ScreenHint\">This screen allows you to edit the details of the ");


            
            #line 26 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
                                                                         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" job search.</div>");



WriteLiteral("<br />\r\n");


            
            #line 27 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 29 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
 using (Html.BeginForm(MVC.JobSearch.Edit(), FormMethod.Post, new { @class = "editform" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        ");


            
            #line 32 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
   Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n        <div class=\"required\">\r\n            <label>Job Search Title</labe" +
"l>\r\n            ");


            
            #line 36 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
       Write(Html.TextBoxFor(x => x.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"required\">\r\n            <label>Descriptio" +
"n\r\n            </label>\r\n            ");


            
            #line 42 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
       Write(Html.TextAreaFor(x => x.Description, new { rows = 4 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        \r\n        <div class=\"submit\">\r\n            <input type" +
"=\"submit\" value=\"Submit\" class=\"inputSubmit\" /> &nbsp; &nbsp;\r\n");


            
            #line 47 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
             if (isNewJobSearch)
            {
                
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
           Write(Html.ActionLink("Cancel", MVC.JobSearch.Index()));

            
            #line default
            #line hidden
            
            #line 49 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
                                                                 ;
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
           Write(Html.ActionLink("Cancel", MVC.JobSearch.Details(Model.Id)));

            
            #line default
            #line hidden
            
            #line 53 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
                                                                           ;
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </fieldset>\r\n");


            
            #line 58 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Edit.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
