#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.JobSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/JobSearch/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.Entities.JobSearch>
    {
        public Edit()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\JobSearch\Edit.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";
    bool isNewJobSearch = Model.Id == 0;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 8 "..\..\Views\JobSearch\Edit.cshtml"
 using (Html.PageInfoBox(false))
{
    using (Html.BeginForm(MVC.JobSearch.Edit())) 
    {
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\JobSearch\Edit.cshtml"
   Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\JobSearch\Edit.cshtml"
                                  

        using (Html.OuterRow())
        {

            
            #line default
            #line hidden
WriteLiteral("            <h3 class=\"floatLeft\">");


            
            #line 16 "..\..\Views\JobSearch\Edit.cshtml"
                              Write(isNewJobSearch ? "Start Job Search" : "Edit Job Search");

            
            #line default
            #line hidden
WriteLiteral("</h3> \r\n");


            
            #line 17 "..\..\Views\JobSearch\Edit.cshtml"
        }

        using (Html.OuterRow())
        {
            using (Html.ContentArea())
            {

            
            #line default
            #line hidden
WriteLiteral(@"                <p>
                    Your first step is to setup a job search. <br /><br />
                            
                    Interview Tools allows you to organize multiple job searches. Some uses of this are to
                    prganize your job search by year, such as ""2011 Full Time Position"", ""2012 Internship Hunt"", or ""May 2012 Need Part-Time Job""
                    and to organize job search by function, such as ""Sales and Marketing Opportunities"" or ""Engineering Job Search""
                </p>    
");


            
            #line 30 "..\..\Views\JobSearch\Edit.cshtml"
            }
        }

        using (Html.OuterRow())
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"floatLeft infoSpan\">\r\n                ");


            
            #line 36 "..\..\Views\JobSearch\Edit.cshtml"
           Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 38 "..\..\Views\JobSearch\Edit.cshtml"
        }

        using (Html.OuterRow())
        {
            Html.FormField("Title:", Html.TextBoxFor(x => x.Name, new { @class = "info" }));
        }

        using (Html.OuterRow())
        {
            Html.FormField("Description:", @Html.TextAreaFor(x => x.Description, new { @class = "textAreaInfo" }));
        }

        using (Html.OuterRow())
        {
            using(Html.FormButtonArea())
            {

            
            #line default
            #line hidden
WriteLiteral("                <input type=\"submit\" value=\"Save\" />\r\n");


            
            #line 55 "..\..\Views\JobSearch\Edit.cshtml"
            }
        }
    }
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
