#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.JobSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/JobSearch/Search.cshtml")]
    public class Search : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.PerformedSearchViewModel>
    {
        public Search()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
  
    ViewBag.Title = "Search Results";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid2 floatLeft\">\r\n    <div class=\"taskHeader\">\r\n        <h3>Search" +
" Results</h3>\r\n    </div>\r\n\r\n    <h3 class=\"taskCalls\">Companies</h3>\r\n\r\n    <di" +
"v id=\"taskRole\">\r\n        <ul>\r\n");


            
            #line 16 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
             if (Model.Results.Companies.Count == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <div class=\"taskName\">No companies matc" +
"hed the search terms</div>\r\n                </li>\r\n");


            
            #line 21 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 23 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
             foreach (var company in Model.Results.Companies)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <a href=\"");


            
            #line 26 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                        Write(Url.Action(MVC.Company.Details(company.Id)));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <div class=\"taskName\">");


            
            #line 27 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                         Write(company.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div class=\"taskDescription\">");


            
            #line 28 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                                Write(Html.ShortString(company.Notes, 90));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </a>\r\n                </li>\r\n");


            
            #line 31 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n\r\n    <h3 class=\"taskCalls\">Contacts</h3>\r\n\r\n    <div " +
"id=\"taskRole\">\r\n        <ul>\r\n");


            
            #line 39 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
             if (Model.Results.Contacts.Count == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <div class=\"taskName\">No contacts match" +
"ed the search terms</div>\r\n                </li>\r\n");


            
            #line 44 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 46 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
             foreach (var contact in Model.Results.Contacts )
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <a href=\"");


            
            #line 49 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                        Write(Url.Action(MVC.Contact.Details(contact.Id)));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <div class=\"taskName\">");


            
            #line 50 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                         Write(contact.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div class=\"taskDescription\">Employee of ");


            
            #line 51 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                                            Write(contact.Company.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div class=\"taskDescription\">");


            
            #line 52 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                                Write(Html.ShortString(contact.Notes, 90));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </a>\r\n                </li>\r\n");


            
            #line 55 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n\r\n    <h3 class=\"taskCalls\">Tasks</h3>\r\n\r\n    <div id=" +
"\"taskRole\">\r\n        <ul>\r\n");


            
            #line 63 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
             if (Model.Results.Contacts.Count == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <div class=\"taskName\">No tasks matched " +
"the search terms</div>\r\n                </li>\r\n");


            
            #line 68 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 70 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
             foreach (var task in Model.Results.Tasks)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <a href=\"");


            
            #line 73 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                        Write(Url.Action(MVC.Task.Details(task.Id)));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <div class=\"taskName\">");


            
            #line 74 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                         Write(task.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div class=\"taskDescription\">Company: ");


            
            #line 75 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                                         Write(task.Company.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


            
            #line 77 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                         if (task.Contact != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"taskDescription\">Contact: ");


            
            #line 79 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                                             Write(task.Contact.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 80 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"taskDescription\">");


            
            #line 82 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
                                                Write(Html.ShortString(task.Notes, 90));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </a>\r\n                </li>\r\n");


            
            #line 85 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\JobSearch\Search.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
