#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Company
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/_CompanySidebarDisplay.cshtml")]
    public class _CompanySidebarDisplay : System.Web.Mvc.WebViewPage<MyJobLeads.DomainModel.Entities.Company>
    {
        public _CompanySidebarDisplay()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\_CompanySidebarDisplay.cshtml"
  
    // Form company location string
    bool citySpecified = !string.IsNullOrWhiteSpace(Model.City);
    bool stateSpecified = !string.IsNullOrWhiteSpace(Model.State);
    bool zipSpecified = !string.IsNullOrWhiteSpace(Model.Zip);

    string location = string.Empty;
    if (citySpecified && stateSpecified) { location = string.Concat(Model.City, ", ", Model.State, " "); }
    else if (citySpecified) { location = Model.City + " "; }
    else if (stateSpecified) { location = Model.State + " "; }

    if (zipSpecified) { location += Model.Zip; }


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");


            
            #line 17 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\_CompanySidebarDisplay.cshtml"
Write(Html.ActionLink(Model.Name, MVC.Company.Details(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\'s Summary</h2>\r\n");


            
            #line 18 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\_CompanySidebarDisplay.cshtml"
Write(Html.ActionLink("Edit Details", MVC.Company.Edit(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<br /><br />\r\n\r\n<p>\r\n    Phone: ");


            
            #line 23 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\_CompanySidebarDisplay.cshtml"
      Write(Model.Phone);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n    Location: ");


            
            #line 24 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\_CompanySidebarDisplay.cshtml"
         Write(location);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n    Notes: ");


            
            #line 25 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\_CompanySidebarDisplay.cshtml"
      Write(Model.Notes);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n</p>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
