#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Company
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyJobLeads.Infrastructure.HtmlHelpers;
    using Telerik.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Companies.CompanyDisplayViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
  
    ViewBag.Title = "Company: " + Model.Name;


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"lineSeperater\"> \r\n        <div " +
"class=\"pageInfoBox\">\r\n            <div class=\"grid3 marginBottom_10 marginAuto f" +
"loatLeft\"> \r\n                <h3 class=\"floatLeft\">");


            
            #line 11 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                 Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3> \r\n                ");


            
            #line 12 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
           Write(Html.ActionLink("Edit Details", MVC.Company.Edit(Model.Id), new { @class = "floatRight blueLinks", title = "Edit Details" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div> \r\n\r\n            <div class=\"grid3 marginBottom_10 floatLeft\"" +
"> \r\n                <div class=\"grid4 floatLeft\"> \r\n                    <p class" +
"=\"greyHighlight\">Phone: <span class=\"setTask\">");


            
            #line 17 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                                     Write(Model.Phone);

            
            #line default
            #line hidden
WriteLiteral("</span></p> \r\n                    <p class=\"greyHighlight\">Location: <span class=" +
"\"setTask\">");


            
            #line 18 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                                        Write(Model.Location);

            
            #line default
            #line hidden
WriteLiteral("</span></p> \r\n                </div> \r\n                <div class=\"grid4 floatRig" +
"ht\"> \r\n                    <p class=\"greyHighlight\">Status: <span class=\"setTask" +
"\">");


            
            #line 21 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                                      Write(Model.LeadStatus);

            
            #line default
            #line hidden
WriteLiteral(@"</span></p> 
                </div> 
            </div> 
                                
            <div class=""grid3 marginBottom_10 floatLeft""> 
                <div class=""floatLeft"">
                    <p class=""greyHighlight"">Notes: 
                        <span class=""setTask"">");


            
            #line 28 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                         Write(Html.Raw(Html.Encode(Model.Notes).Replace(Environment.NewLine, "<br />")));

            
            #line default
            #line hidden
WriteLiteral(@"</span>
                    </p>
                </div> 
            </div> 

            <div class=""clear""></div>
        </div> 
    </div> 
</div> 
                    
<div class=""grid1 marginTop_20 floatLeft""> 
    <div class=""grid2 floatLeft""> 

");


            
            #line 41 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
         if (Model.OpenTasks.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <h3 class=\"taskCalls\">Open Tasks</h3> \r\n");



WriteLiteral("            <div id=\"taskRole\"> \r\n                <ul>\r\n");


            
            #line 46 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                     foreach (var task in Model.OpenTasks.OrderBy(x => x.DueDate))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li>\r\n                            <div class=\"greyHighlig" +
"ht date\">");


            
            #line 49 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                       Write(Html.GetDueDateString(task.DueDate));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"taskName\">");


            
            #line 50 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                             Write(task.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <p class=\"taskDescription\">");


            
            #line 51 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                  Write(task.AssociatedWith);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p>");


            
            #line 52 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                          Write(Html.ShortString(task.Notes, 110));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            ");


            
            #line 53 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                       Write(Html.ActionLink("View Task", MVC.Task.Details(task.Id), new { @class = "blueLinks viewContact" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </li>\r\n");


            
            #line 55 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul> \r\n             </div>\t\r\n");


            
            #line 58 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("                \r\n");


            
            #line 60 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
         if (Model.CompletedTasks.Count > 0)
        {           

            
            #line default
            #line hidden
WriteLiteral("            <h3 class=\"taskCalls\">Completed Tasks</h3> \r\n");



WriteLiteral("            <div id=\"taskRole\"> \r\n                <ul>\r\n");


            
            #line 65 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                     foreach (var task in Model.CompletedTasks.OrderBy(x => x.CompletionDate))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li>\r\n                            <div class=\"greyHighlig" +
"ht date\">Completed</div>\r\n                            <div class=\"taskName\">");


            
            #line 69 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                             Write(task.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <p class=\"taskDescription\">");


            
            #line 70 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                  Write(task.AssociatedWith);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p>");


            
            #line 71 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                          Write(Html.ShortString(task.Notes, 110));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            ");


            
            #line 72 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                       Write(Html.ActionLink("View Task", MVC.Task.Details(task.Id), new { @class = "blueLinks viewContact" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </li>\r\n");


            
            #line 74 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul>  \r\n            </div>                        \r\n");


            
            #line 77 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        \r\n    </div> \r\n                    \r\n    <div class=\"grid2 floatRight\"> \r" +
"\n        <div class=\"contactsPositionsNv\"><a class=\"active\" href=\"\" title=\"Conta" +
"cts\">Contacts</a> | <a href=\"#\" title=\"Positions\">Positions</a></div>\r\n        ");


            
            #line 83 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
   Write(Html.ActionLink("Add New Contact", MVC.Contact.Add(Model.Id), new { @class = "add blueLinks" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            \r\n        <div id=\"contactsList\"> \r\n            <ul" +
"> \r\n");


            
            #line 87 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                 foreach (var contact in Model.Contacts.OrderBy(x => x.Name))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li> \r\n                        <div class=\"contactName\">");


            
            #line 90 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                            Write(contact.Name);

            
            #line default
            #line hidden
WriteLiteral(" <span></span></div> \r\n                        <p><span class=\"greyHighlight\">Dir" +
"ect:</span> ");


            
            #line 91 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                                 Write(contact.DirectPhone);

            
            #line default
            #line hidden
WriteLiteral(" <span class=\"greyHighlight\">Mobile:</span> ");


            
            #line 91 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                                                                                                                                 Write(contact.MobilePhone);

            
            #line default
            #line hidden
WriteLiteral("</p> \r\n                        <p>");


            
            #line 92 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                      Write(Html.ShortString(contact.Notes, 110));

            
            #line default
            #line hidden
WriteLiteral("</p> \r\n                        ");


            
            #line 93 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                   Write(Html.ActionLink("View Contact", MVC.Contact.Details(contact.Id), new { @class = "blueLinks viewContact" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li> \r\n");


            
            #line 95 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\Details.cshtml"
                }             

            
            #line default
            #line hidden
WriteLiteral("            </ul> \r\n        </div> \r\n    </div> \r\n</div> ");


        }
    }
}
#pragma warning restore 1591
