#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Views.Company
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Company/List.cshtml")]
    public class List : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Companies.JobSearchCompanyListViewModel>
    {
        public List()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\List.cshtml"
  
    ViewBag.Title = "Company List";
    string companyWord = Model.Companies.Count == 1 ? "company" : "companies";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Company List</h2>\r\n<hr />\r\n\r\n");


            
            #line 11 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\List.cshtml"
Write(Html.ActionLink("Add A Company", MVC.Company.Add(Model.JobSearchId)));

            
            #line default
            #line hidden
WriteLiteral(" <br /><br />\r\n\r\nYou have ");


            
            #line 13 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\List.cshtml"
    Write(Model.Companies.Count);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 13 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\List.cshtml"
                           Write(companyWord);

            
            #line default
            #line hidden
WriteLiteral(" entered.\r\n<ul>\r\n");


            
            #line 15 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\List.cshtml"
     foreach (var company in Model.Companies)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>");


            
            #line 17 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\List.cshtml"
       Write(Html.ActionLink(company.Name, MVC.Company.Details(company.Id)));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");


            
            #line 18 "C:\Users\KallDrexx\Documents\Projects\MyJobLeads\MyJobLeads\Views\Company\List.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
