#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobLeads.Areas.Organization.Views.Milestone
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Organization/Views/Milestone/Update.cshtml")]
    public class Update : System.Web.Mvc.WebViewPage<MyJobLeads.ViewModels.Milestones.EditMilestoneViewModel>
    {
        public Update()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
  
    string title = Model.Id == 0 ? "Create Milestone" : "Edit Milestone";
    ViewBag.Title = title;


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid1 floatLeft\"> \r\n    <div class=\"pageInfoBox\"> \r\n");


            
            #line 10 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
         using (Html.BeginForm(MVC.Organization.Milestone.Update())) 
        {
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
       Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                      
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 marginAuto floatLeft\"> \r\n          " +
"      <h3 class=\"floatLeft\">");


            
            #line 15 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                 Write(title);

            
            #line default
            #line hidden
WriteLiteral("</h3> \r\n            </div> \r\n");


            
            #line 17 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 marginAuto floatleft\">\r\n           " +
"     <div class=\"floatLeft infoSpan\">\r\n                    ");


            
            #line 20 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
               Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");


            
            #line 23 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Title:</p>\r\n                    <div " +
"class=\"infoSpan\">");


            
            #line 26 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextBoxFor(x => x.Title, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n\r\n                <div class=\"floatLeft pageInfo" +
"SecondColumn\"><p class=\"greyHighlight\">Previous Milestone:</p>\r\n                " +
"    <div class=\"infoSpan\">");


            
            #line 30 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.DropDownListFor(x => x.PreviousMilestoneId, Model.AvailableMilestoneList));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div> \r\n");


            
            #line 33 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Number of Companies:</p>\r\n           " +
"         <div class=\"infoSpan\">");


            
            #line 36 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextBoxFor(x => x.JobSearchMetrics.NumCompaniesCreated, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n\r\n                <div class=\"floatLeft pageInfo" +
"SecondColumn\"><p class=\"greyHighlight\">Number of Contacts:</p>\r\n                " +
"    <div class=\"infoSpan\">");


            
            #line 40 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextBoxFor(x => x.JobSearchMetrics.NumContactsCreated, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n            </div> \r\n");


            
            #line 43 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Number of Apply To Firm Tasks Created" +
":</p>\r\n                    <div class=\"infoSpan\">");


            
            #line 46 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextBoxFor(x => x.JobSearchMetrics.NumApplyTasksCreated, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n\r\n                <div class=\"floatLeft pageInfo" +
"SecondColumn\"><p class=\"greyHighlight\">Number of Apply To Firm Tasks Completed:<" +
"/p>\r\n                    <div class=\"infoSpan\">");


            
            #line 50 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextBoxFor(x => x.JobSearchMetrics.NumApplyTasksCompleted, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n            </div> \r\n");


            
            #line 53 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Number of Phone Interview Tasks Creat" +
"ed:</p>\r\n                    <div class=\"infoSpan\">");


            
            #line 56 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextBoxFor(x => x.JobSearchMetrics.NumPhoneInterviewTasksCreated, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n\r\n                <div class=\"floatLeft pageInfo" +
"SecondColumn\"><p class=\"greyHighlight\">Number of In-Person Interview Tasks Creat" +
"ed:</p>\r\n                    <div class=\"infoSpan\">");


            
            #line 60 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextBoxFor(x => x.JobSearchMetrics.NumInPersonInterviewTasksCreated, new { @class = "info" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n            </div> \r\n");


            
            #line 63 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Instructional Text For Milestone:</p>" +
"\r\n                    <div class=\"infoSpan\">");


            
            #line 66 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextAreaFor(x => x.Instructions, new { @class = "textAreaInfo" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n            </div> \r\n");


            
            #line 69 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_10 floatLeft\"> \r\n                <div " +
"class=\"floatLeft\"><p class=\"greyHighlight\">Text Displayed When Milestone Complet" +
"ed:</p>\r\n                    <div class=\"infoSpan\">");


            
            #line 72 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                     Write(Html.TextAreaFor(x => x.CompletionDisplay, new { @class = "textAreaInfo" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div> \r\n            </div>\r\n");


            
            #line 75 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid3 marginBottom_20 floatLeft\"> \r\n                <div " +
"class=\"submitBTN \">\r\n                    <input type=\"submit\" value=\"Save\" /> &n" +
"bsp; &nbsp;\r\n");


            
            #line 79 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                     if (Model.Id == 0)
                    {
                        
            
            #line default
            #line hidden
            
            #line 81 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                   Write(Html.ActionLink("Cancel", MVC.Organization.Milestone.List()));

            
            #line default
            #line hidden
            
            #line 81 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                                                                     
                    }

                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 86 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                   Write(Html.ActionLink("Cancel", MVC.Organization.Milestone.Details(Model.Id)));

            
            #line default
            #line hidden
            
            #line 86 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
                                                                                                
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div> \r\n            </div> \r\n");


            
            #line 90 "..\..\Areas\Organization\Views\Milestone\Update.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div> \r\n    </div> \r\n</div> \r\n");


        }
    }
}
#pragma warning restore 1591
